#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://save.umwblogs.org/ \
https://bjohnsto.umwblogs.org/ \
https://anthologize.umwblogs.org/ \
https://fortmonroe.hamptondigitalhumanities.org/ \
https://wgst.umwblogs.org/ \
https://marchinghome2010.umwblogs.org/ \
https://ushistfilm2010.umwblogs.org/ \
https://unitedstatesforeignpolicy.umwblogs.org/ \
https://psychofwomenfall10.umwblogs.org/ \
https://umwtheme.umwblogs.org/ \
https://sixthsmith.umwblogs.org/ \
https://jsainz.umwblogs.org/ \
https://historyofpsych.umwblogs.org/ \
https://southernliterature.umwblogs.org/ \
https://naltikriti.umwblogs.org/ \
https://robyager1.umwblogs.org/ \
https://tsuggs.umwblogs.org/ \
https://copof10.umwblogs.org/ \
https://asianamlitf10.umwblogs.org/ \
https://ethicslitfsemf10.umwblogs.org/ \
https://eschermathfall2010.umwblogs.org/ \
https://egypt.umwblogs.org/ \
https://careerscpsc.umwblogs.org/ \
https://rosie.umwblogs.org/ \
https://laceibamfi.umwblogs.org/ \
https://cpsc110.umwblogs.org/ \
https://clublacrosse.umwblogs.org/ \
https://sara.umwblogs.org/ \
https://jinetita.umwblogs.org/ \
https://madden.umwblogs.org/ \
https://clevinehistandfilm.umwblogs.org/ \
https://cinemeg.umwblogs.org/ \
https://smallgroup2010.umwblogs.org/ \
https://midtermexperts.umwblogs.org/ \
https://amandalo90.umwblogs.org/ \
https://publicspeaking2010.umwblogs.org/ \
https://wbowler.umwblogs.org/ \
https://mmiller6.umwblogs.org/ \
https://envirrhet2010.umwblogs.org/ \
https://amankarios1.umwblogs.org/ \
https://gkimballoralhistory.umwblogs.org/ \
https://swrenn.umwblogs.org/ \
https://anniegro.umwblogs.org/ \
https://pppp.umwblogs.org/ \
https://jem229.umwblogs.org/ \
https://azarzeck.umwblogs.org/ \
https://sdemetro.umwblogs.org/ \
https://snoopy50.umwblogs.org/ \
https://1102hobnail.umwblogs.org/ \
https://meganwhistfilm.umwblogs.org/ \
https://jenn471.umwblogs.org/ \
https://meganw471.umwblogs.org/ \
https://umwpac.umwblogs.org/ \
https://ds106.umwblogs.org/ \
https://clomax3.umwblogs.org/ \
https://heather303.umwblogs.org/ \
https://joycarter.umwblogs.org/ \
https://andrewh.umwblogs.org/ \
https://meginthemovies.umwblogs.org/ \
https://dmckenn2.umwblogs.org/ \
https://emilyhamst201.umwblogs.org/ \
https://westernciv2.umwblogs.org/ \
https://hawkeye15scotty.umwblogs.org/ \
https://rmont.umwblogs.org/ \
https://marymoncure.umwblogs.org/ \
https://cukincaid.umwblogs.org/ \
https://bsims.umwblogs.org/ \
https://csims.umwblogs.org/ \
https://calabresen.umwblogs.org/ \
https://mcbiwer.umwblogs.org/ \
https://edward.umwblogs.org/ \
https://ktaylor2.umwblogs.org/ \
https://leahembrey.umwblogs.org/ \
https://bsisk.umwblogs.org/ \
https://hdiaz.umwblogs.org/ \
https://historyonscreen.umwblogs.org/ \
https://vantage.umwblogs.org/ \
https://sonny5484.umwblogs.org/ \
https://carynamst303.umwblogs.org/ \
https://wboyle3617.umwblogs.org/ \
https://ryand730.umwblogs.org/ \
https://hlwhite.umwblogs.org/ \
https://myblogfor329.umwblogs.org/ \
https://cschulz.umwblogs.org/ \
https://calvinsherwood.umwblogs.org/ \
https://rowleyoralhistory.umwblogs.org/ \
https://cee719.umwblogs.org/ \
https://travels.umwblogs.org/ \
https://ericoralhistory.umwblogs.org/ \
https://seanr.umwblogs.org/ \
https://lbevis.umwblogs.org/ \
https://historytravels.umwblogs.org/ \
https://kallen3.umwblogs.org/ \
https://htaylor299.umwblogs.org/ \
https://annaholman.umwblogs.org/ \
https://csafritt.umwblogs.org/ \
https://eunderwo.umwblogs.org/ \
https://cbusfp3.umwblogs.org/ \
https://otirb.umwblogs.org/ \
https://acastro1.umwblogs.org/ \
https://javic.umwblogs.org/ \
https://sarahsmile.umwblogs.org/ \
https://davidcasteel201.umwblogs.org/ \
https://gtravis.umwblogs.org/ \
https://jakeg.umwblogs.org/ \
https://cmurray.umwblogs.org/ \
https://lookatme.umwblogs.org/ \
https://labellevie.umwblogs.org/ \
https://katiedigiarts.umwblogs.org/ \
https://marlenedigiarts.umwblogs.org/ \
https://kaylaeliseart.umwblogs.org/ \
https://ninadigiarts.umwblogs.org/ \
https://artonscreen.umwblogs.org/ \
https://torismith.umwblogs.org/ \
https://digitalapproachesclawlor.umwblogs.org/ \
https://msicola13.umwblogs.org/ \
https://psychedelia.umwblogs.org/ \
https://cfredrickson.umwblogs.org/ \
https://joos820.umwblogs.org/ \
https://sasquatchlives.umwblogs.org/ \
https://jhampel.umwblogs.org/ \
https://ushistoryandfilm.umwblogs.org/ \
https://alv471.umwblogs.org/ \
https://acscharf.umwblogs.org/ \
https://abeer.umwblogs.org/ \
https://fortmonroe2.hamptondigitalhumanities.org/ \
https://macwoodruff.umwblogs.org/ \
https://jbrown5.umwblogs.org/ \
https://ggatt1zw.umwblogs.org/ \
https://lreed2.umwblogs.org/ \
https://anivelisse.umwblogs.org/ \
https://vmoody.umwblogs.org/ \
https://mattbaldwin.umwblogs.org/ \
https://connorfinnerty.umwblogs.org/ \
https://smendel.umwblogs.org/ \
https://cchau201.umwblogs.org/ \
https://masonm.umwblogs.org/ \
https://tjenning.umwblogs.org/ \
https://kcooke2.umwblogs.org/ \
https://sakinard.umwblogs.org/ \
https://choga1op.umwblogs.org/ \
https://atuminello80.umwblogs.org/ \
https://sbunch2.umwblogs.org/ \
https://hsmith.umwblogs.org/ \
https://kroper.umwblogs.org/ \
https://jacobdm.umwblogs.org/ \
https://ckilla.umwblogs.org/ \
https://dconti.umwblogs.org/ \
https://ereed1.umwblogs.org/ \
https://rhauser.umwblogs.org/ \
https://elampe.umwblogs.org/ \
https://madim.umwblogs.org/ \
https://pampetzold.umwblogs.org/ \
https://willardhist299.umwblogs.org/ \
https://pnova.umwblogs.org/ \
https://xenos.umwblogs.org/ \
https://breyes.umwblogs.org/ \
https://zizeksbeard.umwblogs.org/ \
https://upandaway.umwblogs.org/ \
https://lukasschroeder.umwblogs.org/ \
https://nbeasley8722.umwblogs.org/ \
https://creativecupcake.umwblogs.org/ \
https://sharsha.umwblogs.org/ \
https://hmcgrath.umwblogs.org/ \
https://wick.umwblogs.org/ \
https://kmayheweng302.umwblogs.org/ \
https://cgray2.umwblogs.org/ \
https://wchang12.umwblogs.org/ \
https://brookedurbin.umwblogs.org/ \
https://andreaf.umwblogs.org/ \
https://althky.umwblogs.org/ \
https://shall2.umwblogs.org/ \
https://aleonard.umwblogs.org/ \
https://brendajoyceking.umwblogs.org/ \
https://runforrestrun.umwblogs.org/ \
https://morganharding.umwblogs.org/ \
https://glitterbug.umwblogs.org/ \
https://emontgo2.umwblogs.org/ \
https://tdavidson.umwblogs.org/ \
https://cobrien25.umwblogs.org/ \
https://jcrystle.umwblogs.org/ \
https://clang.umwblogs.org/ \
https://valan.umwblogs.org/ \
https://jreese.umwblogs.org/ \
https://melle.umwblogs.org/ \
https://emlatte.umwblogs.org/ \
https://musicdemo.umwblogs.org/ \
https://crazehloreh.umwblogs.org/ \
https://scoogles302poetry.umwblogs.org/ \
https://phatfunk.umwblogs.org/ \
https://rflaks98.umwblogs.org/ \
https://julieallbeck.umwblogs.org/ \
https://bpurdy.umwblogs.org/ \
https://thomasellaintrotocreativewriting.umwblogs.org/ \
https://sledrinblog.umwblogs.org/ \
https://bchitty.umwblogs.org/ \
https://qdillmworks.umwblogs.org/ \
https://amorin2.umwblogs.org/ \
https://hhyler.umwblogs.org/ \
https://etavino.umwblogs.org/ \
https://rogers.umwblogs.org/ \
https://hkasseba.umwblogs.org/ \
https://unknownspirit758.umwblogs.org/ \
https://ajoppich.umwblogs.org/ \
https://msicola.umwblogs.org/ \
https://batman.umwblogs.org/ \
https://lonnie.umwblogs.org/ \
https://samjordan.umwblogs.org/ \
https://londonbridget.umwblogs.org/ \
https://oshkoshbgosh.umwblogs.org/ \
https://love2write.umwblogs.org/ \
https://imagine.umwblogs.org/ \
https://housingandsociety.umwblogs.org/ \
https://dodell.umwblogs.org/ \
https://allen.umwblogs.org/ \
https://finance.umwblogs.org/ \
https://oralhist471.umwblogs.org/ \
https://classcouncil.umwblogs.org/ \
https://joliver.umwblogs.org/ \
https://kreederfilm.umwblogs.org/ \
https://maroskie.umwblogs.org/ \
https://tpugh.umwblogs.org/ \
https://erinburke.umwblogs.org/ \
https://shanna3.umwblogs.org/ \
https://lredding.umwblogs.org/ \
https://471socialtheoryschweers.umwblogs.org/ \
https://vidaaustinamst201.umwblogs.org/ \
https://tierratheory.umwblogs.org/ \
https://kristindoestheory.umwblogs.org/ \
https://kmayhewspan413.umwblogs.org/ \
https://kflynn.umwblogs.org/ \
https://southspan413.umwblogs.org/ \
https://klanewala.umwblogs.org/ \
https://justine2.umwblogs.org/ \
https://umwmusic.umwblogs.org/ \
https://gnecco.umwblogs.org/ \
https://gregonliberty.umwblogs.org/ \
https://kateboggs.umwblogs.org/ \
https://exigo.umwblogs.org/ \
https://kdawson.umwblogs.org/ \
https://thaywood19.umwblogs.org/ \
https://rdhanar2.umwblogs.org/ \
https://stuart.umwblogs.org/ \
https://prosesam.umwblogs.org/ \
https://sarahponshop.umwblogs.org/ \
https://tothepoint.umwblogs.org/ \
https://therussiansarecoming123.umwblogs.org/ \
https://pmullen57.umwblogs.org/ \
https://twright.umwblogs.org/ \
https://tomwright.umwblogs.org/ \
https://aholman.umwblogs.org/ \
https://misespieces.umwblogs.org/ \
https://cbarbery.umwblogs.org/ \
https://mattgonzalez8947.umwblogs.org/ \
https://scarlet.umwblogs.org/ \
https://bart1meus.umwblogs.org/ \
https://stcampbell.umwblogs.org/ \
https://maxton.umwblogs.org/ \
https://howardcapon.umwblogs.org/ \
https://alester1.umwblogs.org/ \
https://drewsneverendingstory.umwblogs.org/ \
https://engl202g01ncochran.umwblogs.org/ \
https://asalatino.umwblogs.org/ \
https://masulli.umwblogs.org/ \
https://ddowdy.umwblogs.org/ \
https://cheizer.umwblogs.org/ \
https://myssoula.umwblogs.org/ \
https://apocalypsenow.umwblogs.org/ \
https://deriddler.umwblogs.org/ \
https://lms.umwblogs.org/ \
https://leelzebub.umwblogs.org/ \
https://mkay.umwblogs.org/ \
https://clew.umwblogs.org/ \
https://dklein.umwblogs.org/ \
https://cassandralewis2.umwblogs.org/ \
https://isaacwhalen.umwblogs.org/ \
https://stayclassy.umwblogs.org/ \
https://oirakoze19.umwblogs.org/ \
https://umwcrs.umwblogs.org/ \
https://mchiu.umwblogs.org/ \
https://nathanbent.umwblogs.org/ \
https://bnsveum.umwblogs.org/ \
https://slee4.umwblogs.org/ \
https://malc.umwblogs.org/ \
https://czamora.umwblogs.org/ \
https://andif.umwblogs.org/ \
https://prowane.umwblogs.org/ \
https://vyale329.umwblogs.org/ \
https://jman289.umwblogs.org/ \
https://spainmcrelations.umwblogs.org/ \
https://caitland.umwblogs.org/ \
https://truthbombs.umwblogs.org/ \
https://lhamilto.umwblogs.org/ \
https://wadialkabir.umwblogs.org/ \
https://writingaboutfood.umwblogs.org/ \
https://umwresearch.umwblogs.org/ \
https://umwdistancelearning.umwblogs.org/ \
https://polack.umwblogs.org/ \
https://mujeresycaridad.umwblogs.org/ \
https://umweducation.umwblogs.org/ \
https://power.umwblogs.org/ \
https://historyofpsychstephaniewatkins.umwblogs.org/ \
https://laurensdaniel.umwblogs.org/ \
https://projectivetests.umwblogs.org/ \
https://emergingadulthood.umwblogs.org/ \
https://bdkmsw.umwblogs.org/ \
https://clinical.umwblogs.org/ \
https://forensicpsych.umwblogs.org/ \
https://insanityplea.umwblogs.org/ \
https://mentalillness.umwblogs.org/ \
https://kidsandmeds.umwblogs.org/ \
https://quackery.umwblogs.org/ \
https://khughes360.umwblogs.org/ \
https://diversity.umwblogs.org/ \
https://lminhui.umwblogs.org/ \
https://nbemis.umwblogs.org/ \
https://sbachmann360.umwblogs.org/ \
https://sadiespainsmith.umwblogs.org/ \
https://mellinger.umwblogs.org/ \
https://bbkube.umwblogs.org/ \
https://sociologyandhousing.umwblogs.org/ \
https://rosario.umwblogs.org/ \
https://lambersontheory.umwblogs.org/ \
https://cvega.umwblogs.org/ \
https://philipx2.umwblogs.org/ \
https://ethershopf10.umwblogs.org/ \
https://creativeact.umwblogs.org/ \
https://masterplan.umwblogs.org/ \
https://spicytofu.umwblogs.org/ \
https://aberrantjournal.umwblogs.org/ \
https://timezoneslitreview.umwblogs.org/ \
https://twodollarchallenge.org/ \
https://socialmovementsdoc.umwblogs.org/ \
https://paulbutler.umwblogs.org/ \
https://thecreativeact.umwblogs.org/ \
https://fairtrade.umwblogs.org/ \
https://alcovejournal.umwblogs.org/ \
https://jhillman.umwblogs.org/ \
https://profprac.umwblogs.org/ \
https://neuroscience.umwblogs.org/ \
https://wgstoralhistory.umwblogs.org/ \
https://poupeeblanche.umwblogs.org/ \
https://halfmedium.umwblogs.org/ \
https://secretlyrobotic.umwblogs.org/ \
https://dnissim.umwblogs.org/ \
https://shannotated.umwblogs.org/ \
https://buildingtaste.umwblogs.org/ \
https://sustainability.umwblogs.org/ \
https://umwarh.umwblogs.org/ \
https://gmeadows.umwblogs.org/ \
https://jkoniecz.umwblogs.org/ \
https://libs101.umwblogs.org/ \
https://crazymadam.umwblogs.org/ \
https://speakingup.umwblogs.org/ \
https://ychiang.umwblogs.org/ \
https://kalamataolives.umwblogs.org/ \
https://stpumw.umwblogs.org/ \
https://webredesign.umwblogs.org/ \
https://rfrackelton.umwblogs.org/ \
https://americanavantgarde.umwblogs.org/ \
https://jonw00z.umwblogs.org/ \
https://sos.umwblogs.org/ \
https://slipscomb.umwblogs.org/ \
https://thomasellaintrotocreativewritingii.umwblogs.org/ \
https://kateykerns.umwblogs.org/ \
https://daneemusic.umwblogs.org/ \
https://residencelife.umwblogs.org/ \
https://wwieland.umwblogs.org/ \
https://esfuerzodeamor.umwblogs.org/ \
https://pfallon.umwblogs.org/ \
https://americanphilosophy.umwblogs.org/ \
https://thehumananimal2015.umwblogs.org/ \
https://tiana.umwblogs.org/ \
https://thelongview.umwblogs.org/ \
https://genderneutralhousing.umwblogs.org/ \
https://swashbucklingss.umwblogs.org/ \
https://mbagoat.umwblogs.org/ \
https://retroactivenautili.umwblogs.org/ \
https://publicspherewatch.umwblogs.org/ \
https://mixmatched.umwblogs.org/ \
https://openbydesign.umwblogs.org/ \
https://ilikeyourbeard.umwblogs.org/ \
https://transported.umwblogs.org/ \
https://nicethings.umwblogs.org/ \
https://vroycroft.umwblogs.org/ \
https://giantproductions.umwblogs.org/ \
https://lucybain.umwblogs.org/ \
https://history365.umwblogs.org/ \
https://rappscholar.umwblogs.org/ \
https://thecrategallery.umwblogs.org/ \
https://cpsc125.umwblogs.org/ \
https://cpsc430saylor.umwblogs.org/ \
https://newyork.umwblogs.org/ \
https://jlevi.umwblogs.org/ \
https://povertyactionconference.umwblogs.org/ \
https://conversos.umwblogs.org/ \
https://mhershey.umwblogs.org/ \
https://sschroed.umwblogs.org/ \
https://discourse.umwblogs.org/ \
https://katabasis2.umwblogs.org/ \
https://crbarnes.umwblogs.org/ \
https://nhall.umwblogs.org/ \
https://digsto.umwblogs.org/ \
https://bkutsch.umwblogs.org/ \
https://cupofchai.umwblogs.org/ \
https://esundstr.umwblogs.org/ \
https://kmhamerski.umwblogs.org/ \
https://gephy.umwblogs.org/ \
https://tylerherold.umwblogs.org/ \
https://hiddenjemblog.umwblogs.org/ \
https://joannwang.umwblogs.org/ \
https://negativland.umwblogs.org/ \
https://floopsjarofteeth.umwblogs.org/ \
https://lifeafterds106.umwblogs.org/ \
https://helpdrguerrerodecipherdreams.umwblogs.org/ \
https://megz23.umwblogs.org/ \
https://mattandben.umwblogs.org/ \
https://winterclassic.umwblogs.org/ \
https://dhylandwood.umwblogs.org/ \
https://jadeblogs.umwblogs.org/ \
https://popularculture.umwblogs.org/ \
https://hist299.umwblogs.org/ \
https://2011hist325.umwblogs.org/