#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://socialmovementsdoc.umwblogs.org/ \
https://paulbutler.umwblogs.org/ \
https://thecreativeact.umwblogs.org/ \
https://fairtrade.umwblogs.org/ \
https://alcovejournal.umwblogs.org/ \
https://jhillman.umwblogs.org/ \
https://profprac.umwblogs.org/ \
https://neuroscience.umwblogs.org/ \
https://wgstoralhistory.umwblogs.org/ \
https://poupeeblanche.umwblogs.org/ \
https://halfmedium.umwblogs.org/ \
https://secretlyrobotic.umwblogs.org/ \
https://dnissim.umwblogs.org/ \
https://shannotated.umwblogs.org/ \
https://buildingtaste.umwblogs.org/ \
https://sustainability.umwblogs.org/ \
https://umwarh.umwblogs.org/ \
https://gmeadows.umwblogs.org/ \
https://jkoniecz.umwblogs.org/ \
https://libs101.umwblogs.org/ \
https://crazymadam.umwblogs.org/ \
https://speakingup.umwblogs.org/ \
https://ychiang.umwblogs.org/ \
https://kalamataolives.umwblogs.org/ \
https://stpumw.umwblogs.org/ \
https://webredesign.umwblogs.org/ \
https://rfrackelton.umwblogs.org/ \
https://americanavantgarde.umwblogs.org/ \
https://jonw00z.umwblogs.org/ \
https://sos.umwblogs.org/ \
https://slipscomb.umwblogs.org/ \
https://thomasellaintrotocreativewritingii.umwblogs.org/ \
https://kateykerns.umwblogs.org/ \
https://daneemusic.umwblogs.org/ \
https://residencelife.umwblogs.org/ \
https://wwieland.umwblogs.org/ \
https://esfuerzodeamor.umwblogs.org/ \
https://pfallon.umwblogs.org/ \
https://americanphilosophy.umwblogs.org/ \
https://thehumananimal2015.umwblogs.org/ \
https://tiana.umwblogs.org/ \
https://thelongview.umwblogs.org/ \
https://genderneutralhousing.umwblogs.org/ \
https://swashbucklingss.umwblogs.org/ \
https://mbagoat.umwblogs.org/ \
https://retroactivenautili.umwblogs.org/ \
https://publicspherewatch.umwblogs.org/ \
https://mixmatched.umwblogs.org/ \
https://openbydesign.umwblogs.org/ \
https://ilikeyourbeard.umwblogs.org/ \
https://transported.umwblogs.org/ \
https://nicethings.umwblogs.org/ \
https://vroycroft.umwblogs.org/ \
https://giantproductions.umwblogs.org/ \
https://lucybain.umwblogs.org/ \
https://history365.umwblogs.org/ \
https://rappscholar.umwblogs.org/ \
https://thecrategallery.umwblogs.org/ \
https://cpsc125.umwblogs.org/ \
https://cpsc430saylor.umwblogs.org/ \
https://newyork.umwblogs.org/ \
https://jlevi.umwblogs.org/ \
https://povertyactionconference.umwblogs.org/ \
https://conversos.umwblogs.org/ \
https://mhershey.umwblogs.org/ \
https://sschroed.umwblogs.org/ \
https://discourse.umwblogs.org/ \
https://katabasis2.umwblogs.org/ \
https://crbarnes.umwblogs.org/ \
https://nhall.umwblogs.org/ \
https://digsto.umwblogs.org/ \
https://bkutsch.umwblogs.org/ \
https://cupofchai.umwblogs.org/ \
https://esundstr.umwblogs.org/ \
https://kmhamerski.umwblogs.org/ \
https://gephy.umwblogs.org/ \
https://tylerherold.umwblogs.org/ \
https://hiddenjemblog.umwblogs.org/ \
https://joannwang.umwblogs.org/ \
https://negativland.umwblogs.org/ \
https://floopsjarofteeth.umwblogs.org/ \
https://lifeafterds106.umwblogs.org/ \
https://helpdrguerrerodecipherdreams.umwblogs.org/ \
https://megz23.umwblogs.org/ \
https://mattandben.umwblogs.org/ \
https://winterclassic.umwblogs.org/ \
https://dhylandwood.umwblogs.org/ \
https://jadeblogs.umwblogs.org/ \
https://popularculture.umwblogs.org/ \
https://hist299.umwblogs.org/ \
https://2011hist325.umwblogs.org/