#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://juliagoestobeijing.umwblogs.org/ \
https://caitlinbrady.umwblogs.org/ \
https://madelinecain.umwblogs.org/ \
https://evang.umwblogs.org/ \
https://nkblack.umwblogs.org/ \
https://lessonplans.umwblogs.org/ \
https://logic.umwblogs.org/ \
https://dwoodruf.umwblogs.org/ \
https://hist385s12.umwblogs.org/ \
https://hist384s12.umwblogs.org/ \
https://hmartin.umwblogs.org/ \
https://laviemegan.umwblogs.org/ \
https://rdow123.umwblogs.org/ \
https://meghanlgraham.umwblogs.org/ \
https://fewomble.umwblogs.org/ \
https://sofiaspotlight.umwblogs.org/ \
https://pthomas.umwblogs.org/ \
https://jacobbowman.umwblogs.org/ \
https://nutriks.umwblogs.org/ \
https://ewportfolio.umwblogs.org/ \
https://benwrightson.umwblogs.org/ \
https://vilmabustamante.umwblogs.org/ \
https://jhanportfolio.umwblogs.org/ \
https://itsjess.umwblogs.org/ \
https://edrummond.umwblogs.org/ \
https://rarebookhistory.umwblogs.org/ \
https://rwilless.umwblogs.org/ \
https://jgcorrigan.umwblogs.org/ \
https://larabelfield.umwblogs.org/ \
https://christiankarrseportfolio.umwblogs.org/ \
https://rodell.umwblogs.org/ \
https://feministsunitedoncampus.umwblogs.org/ \
https://beccasabroadexperience.umwblogs.org/ \
https://di202.umwblogs.org/ \
https://arts342.umwblogs.org/ \
https://arts470.umwblogs.org/ \
https://artofmathsp2012.umwblogs.org/ \
https://hist328.umwblogs.org/ \
https://vaginamonologues2012.umwblogs.org/ \
https://umwedtechconference.umwblogs.org/ \
https://phil220.umwblogs.org/ \
https://smhillberry.umwblogs.org/ \
https://hist121f13.umwblogs.org/ \
https://acraft.umwblogs.org/ \
https://elit.umwblogs.org/ \
https://hist201s12.umwblogs.org/ \
https://jlmoore.umwblogs.org/ \
https://johnstone.umwblogs.org/ \
https://kahn230.umwblogs.org/ \
https://vectors.umwblogs.org/ \
https://kmdh2012.umwblogs.org/ \
https://themakings.umwblogs.org/ \
https://hnystrom.umwblogs.org/ \
https://ckistner.umwblogs.org/ \
https://indianforeignpolicy.umwblogs.org/ \
https://k21w.umwblogs.org/ \
https://samwarring24.umwblogs.org/ \
https://mcastill.umwblogs.org/ \
https://bfinley.umwblogs.org/ \
https://wmccarry.umwblogs.org/ \
https://acrerie.umwblogs.org/ \
https://cezlock.umwblogs.org/ \
https://denzelm.umwblogs.org/ \
https://camilleeey.umwblogs.org/ \
https://wendypamela.umwblogs.org/ \
https://ransombliss.umwblogs.org/ \
https://entertainment.umwblogs.org/ \
https://abaldys.umwblogs.org/ \
https://michellemartz.umwblogs.org/ \
https://rullah413.umwblogs.org/ \
https://stories2and2secrets.umwblogs.org/ \
https://scoman.umwblogs.org/ \
https://globalfinancialcrisis.umwblogs.org/ \
https://kpdh12.umwblogs.org/ \
https://cassie.umwblogs.org/ \
https://seye012.umwblogs.org/ \
https://span413wsharp.umwblogs.org/ \
https://span413vstclair.umwblogs.org/ \
https://span413ssueiro.umwblogs.org/ \
https://span413zzahl.umwblogs.org/ \
https://span413jcarrillo.umwblogs.org/ \
https://span413vgauss.umwblogs.org/ \
https://span413acameron.umwblogs.org/ \
https://span413mfloresv.umwblogs.org/ \
https://span413mgoins.umwblogs.org/ \
https://span413ekme.umwblogs.org/ \
https://span413jpatterson.umwblogs.org/ \
https://span413yjohnson.umwblogs.org/ \
https://erikburnham.umwblogs.org/ \
https://ccarrolldh2012.umwblogs.org/ \
https://speedingquotes.umwblogs.org/ \
https://heatherhistory.umwblogs.org/ \
https://moderniran.umwblogs.org/ \
https://israelpalestine.umwblogs.org/ \
https://prologjournal.umwblogs.org/ \
https://hpark5.umwblogs.org/ \
https://ahaider.umwblogs.org/ \
https://rjuhan.umwblogs.org/ \
https://erikarose.umwblogs.org/ \
https://artattack.umwblogs.org/ \
https://kaganmcspadden.umwblogs.org/ \
https://khutcheson.umwblogs.org/ \
https://trydigital.umwblogs.org/ \
https://bluemarble.umwblogs.org/ \
https://mymilitaryhistory.umwblogs.org/ \
https://temory.umwblogs.org/ \
https://phelig.umwblogs.org/ \
https://usmeforeignpolicy.umwblogs.org/ \
https://monitor1862.umwblogs.org/ \
https://mmartzdh2012.umwblogs.org/ \
https://pete.umwblogs.org/ \
https://csteiger.umwblogs.org/ \
https://328whiltshire64.umwblogs.org/ \
https://mycreativewritingblog.umwblogs.org/ \
https://sstanfar.umwblogs.org/ \
https://gregorychandler.umwblogs.org/ \
https://ts13.umwblogs.org/ \
https://kcrawfor56.umwblogs.org/ \
https://terrasus.umwblogs.org/ \
https://monkwomenshistory.umwblogs.org/ \
https://katychase.umwblogs.org/ \
https://susiekirschner.umwblogs.org/ \
https://writingcreatively.umwblogs.org/ \
https://scala2012.umwblogs.org/ \
https://katelyncreativewriting.umwblogs.org/ \
https://sharris3.umwblogs.org/ \
https://agrace.umwblogs.org/ \
https://dechard.umwblogs.org/ \
https://islamandthegreatwar.umwblogs.org/ \
https://ffxii.umwblogs.org/ \
https://erict.umwblogs.org/ \
https://mballard4.umwblogs.org/ \
https://mauraslostagain.umwblogs.org/ \
https://tessmcclellan.umwblogs.org/ \
https://jconlon.umwblogs.org/ \
https://glee2.umwblogs.org/ \
https://dclairew.umwblogs.org/ \
https://299history.umwblogs.org/ \
https://marthashistory299.umwblogs.org/ \
https://joeclaytoncr.umwblogs.org/ \
https://shoptilyoudrop.umwblogs.org/ \
https://angelinarat.umwblogs.org/ \
https://cobrienhistoryportfolio.umwblogs.org/ \
https://jrenvironment.umwblogs.org/ \
https://behindthegrind.umwblogs.org/ \
https://haskellang.umwblogs.org/ \
https://kendallsimonpietriresearchhist328.umwblogs.org/ \
https://ddesimon.umwblogs.org/ \
https://umwtimewarp.umwblogs.org/ \
https://marywash1940s.umwblogs.org/ \
https://jaredsmith09.umwblogs.org/ \
https://aaugusti.umwblogs.org/ \
https://1930sresearchlog.umwblogs.org/ \
https://katsena.umwblogs.org/ \
https://carolinebenner.umwblogs.org/ \
https://efritz.umwblogs.org/ \
https://ryangreenwood21.umwblogs.org/ \
https://thevarangianway.umwblogs.org/ \
https://thomas150.umwblogs.org/ \
https://pokemonblue.umwblogs.org/ \
https://abice.umwblogs.org/ \
https://kbusch.umwblogs.org/ \
https://beinggreen.umwblogs.org/ \
https://annewilkins.umwblogs.org/ \
https://ns1950s.umwblogs.org/ \
https://emilyinperu.umwblogs.org/ \
https://sstepano.umwblogs.org/ \
https://chelseagedwards.umwblogs.org/ \
https://historyaccordingtome.umwblogs.org/ \
https://skyrim.umwblogs.org/ \
https://kdandrea.umwblogs.org/ \
https://beccasblog.umwblogs.org/ \
https://catielebouton.umwblogs.org/ \
https://rmorin.umwblogs.org/ \
https://glorifiedthief.umwblogs.org/ \
https://engl302.umwblogs.org/ \
https://digitalapproachesspr19.umwblogs.org/ \
https://awhhiggins.umwblogs.org/ \
https://islamicmovements.umwblogs.org/ \
https://alongerb.umwblogs.org/ \
https://sweidman.umwblogs.org/ \
https://ensignredshirt.umwblogs.org/ \
https://cejohnston.umwblogs.org/ \
https://hbell288.umwblogs.org/ \
https://lmbalderson.umwblogs.org/ \
https://hist328researchlog.umwblogs.org/ \
https://mjankovi.umwblogs.org/ \
https://bsagedy.umwblogs.org/ \
https://katylowdee.umwblogs.org/ \
https://jacquie.umwblogs.org/ \
https://envissues.umwblogs.org/ \
https://ajarrell.umwblogs.org/