#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://dann01z.umwblogs.org/ \
https://gamechangers.umwblogs.org/ \
https://hmoser.umwblogs.org/ \
https://writingaboutsports.umwblogs.org/ \
https://phill.umwblogs.org/ \
https://chucky222.umwblogs.org/ \
https://dance.umwblogs.org/ \
https://fortheoveoflax.umwblogs.org/ \
https://gs2012.umwblogs.org/ \
https://veccia.umwblogs.org/ \
https://tanzania2013.umwblogs.org/ \
https://representingmario.umwblogs.org/ \
https://rugbyscrum.umwblogs.org/ \
https://mandrews.umwblogs.org/ \
https://vexlitjournal.umwblogs.org/ \
https://anneblaine.umwblogs.org/ \
https://findthefish.umwblogs.org/ \
https://aleibowi.umwblogs.org/ \
https://qesthern.umwblogs.org/ \
https://adhd.umwblogs.org/ \
https://historyofpsych12.umwblogs.org/ \
https://rjones5.umwblogs.org/ \
https://adhdhistory.umwblogs.org/ \
https://animalethics.umwblogs.org/ \
https://culturalcapitals.umwblogs.org/ \
https://historyofneuroscience.umwblogs.org/ \
https://qualialitjournal.umwblogs.org/ \
https://musicandarttherapy.umwblogs.org/ \
https://patientrights.umwblogs.org/ \
https://psychologyoftheeast.umwblogs.org/ \
https://audiojournalism.umwblogs.org/ \
https://historyforensicpsych.umwblogs.org/ \
https://edci502teamc.umwblogs.org/ \
https://mperrot.umwblogs.org/ \
https://kallwine.umwblogs.org/ \
https://mentalhealthreport.umwblogs.org/ \
https://graphicnovel.umwblogs.org/ \
https://healthnonprofits.umwblogs.org/ \
https://gamecult.umwblogs.org/ \
https://almw.umwblogs.org/ \
https://nomorebullying.umwblogs.org/ \
https://rosietheriveter.umwblogs.org/ \
https://brookedilauro.umwblogs.org/ \
https://costumeinspiration.umwblogs.org/ \
https://dstoneolson.umwblogs.org/ \
https://zabonhoe.umwblogs.org/ \
https://representingmario3.umwblogs.org/ \
https://modernphilanthropists.umwblogs.org/ \
https://assassinscreedexhibit.umwblogs.org/ \
https://lbpe.umwblogs.org/ \
https://vivalafifa.umwblogs.org/ \
https://fdinger.umwblogs.org/ \
https://jhanseng.umwblogs.org/ \
https://marioparty.umwblogs.org/ \
https://myst.umwblogs.org/ \
https://sarahjoy.umwblogs.org/ \
https://metroid.umwblogs.org/ \
https://minecraftcanonization.umwblogs.org/ \
https://realsmithmix.umwblogs.org/ \
https://cod4mw.umwblogs.org/ \
https://wondertechworld.umwblogs.org/ \
https://tlavonfolsoneportfolio.umwblogs.org/ \
https://findingfashionet.umwblogs.org/ \
https://abarck.umwblogs.org/ \
https://geldridge.umwblogs.org/ \
https://supersmashexhibit.umwblogs.org/ \
https://peterandthewolf.umwblogs.org/ \
https://cpsc110online.umwblogs.org/ \
https://meditation.umwblogs.org/ \
https://cthompspoetry.umwblogs.org/ \
https://codependentstudies.umwblogs.org/ \
https://religionandsex.umwblogs.org/ \
https://spring2013london.umwblogs.org/ \
https://brl13.umwblogs.org/ \
https://bvl13.umwblogs.org/ \
https://jlarochelle31713.umwblogs.org/ \
https://athenagolden.umwblogs.org/ \
https://amst202s13.umwblogs.org/ \
https://sexualitiesofthesouth.umwblogs.org/ \
https://civilwarmemory2013.umwblogs.org/ \
https://cbagwell.umwblogs.org/ \
https://umwedtechconference2013.umwblogs.org/ \
https://2013hist325.umwblogs.org/ \
https://hisp205.umwblogs.org/ \
https://hisp102.umwblogs.org/ \
https://copos13.umwblogs.org/ \
https://whechmerhist466.umwblogs.org/ \
https://longpoems13.umwblogs.org/ \
https://tekla466.umwblogs.org/ \
https://soneil.umwblogs.org/ \
https://china20.umwblogs.org/ \
https://bwebber.umwblogs.org/ \
https://kpatters.umwblogs.org/ \
https://edci500chg.umwblogs.org/ \
https://kpatters2.umwblogs.org/ \
https://bsnookhist466.umwblogs.org/ \
https://kfrost2.umwblogs.org/ \
https://intd501.umwblogs.org/ \
https://aramirez.umwblogs.org/ \
https://springthirteen.umwblogs.org/ \
https://hmelvill.umwblogs.org/ \
https://kpoland.umwblogs.org/ \
https://wyasin.umwblogs.org/ \
https://woliver.umwblogs.org/ \
https://kmohl0ik.umwblogs.org/ \
https://cswaller.umwblogs.org/ \
https://membrain.umwblogs.org/ \
https://pdemitry.umwblogs.org/ \
https://ayildiri19.umwblogs.org/ \
https://kjenkins.umwblogs.org/ \
https://kjenkins506.umwblogs.org/ \
https://documentary.umwblogs.org/ \
https://kmohl0ik2.umwblogs.org/ \
https://cewhist471a.umwblogs.org/ \
https://lauracp.umwblogs.org/ \
https://rere22.umwblogs.org/ \
https://ndobson31713.umwblogs.org/ \
https://jhylan.umwblogs.org/ \
https://missbsreflection.umwblogs.org/ \
https://withers1020.umwblogs.org/ \
https://jessrva.umwblogs.org/ \
https://kerriepastell.umwblogs.org/ \
https://hyoung914.umwblogs.org/ \
https://dpendleton.umwblogs.org/ \
https://mmalok.umwblogs.org/ \
https://adavis6.umwblogs.org/ \
https://kevans3.umwblogs.org/ \
https://fae506.umwblogs.org/ \
https://proudmarinemom.umwblogs.org/ \
https://gbennett30.umwblogs.org/ \
https://rcote31713.umwblogs.org/ \
https://kdekker.umwblogs.org/ \
https://sociologyofbody2013.umwblogs.org/ \
https://jbednarc.umwblogs.org/ \
https://thaliaveizaga.umwblogs.org/ \
https://mtraylor31713.umwblogs.org/ \
https://wrogerschineseculturalhistory.umwblogs.org/ \
https://exploringtheenvironment.umwblogs.org/ \
https://kaycee.umwblogs.org/ \
https://classroomtech.umwblogs.org/ \
https://hmirzada31713.umwblogs.org/ \
https://elusivehymen.umwblogs.org/ \
https://kaylerstudent.umwblogs.org/ \
https://aclark35.umwblogs.org/ \
https://rmcghee31713.umwblogs.org/ \
https://crerietech.umwblogs.org/ \
https://ckyhl.umwblogs.org/ \
https://composition.umwblogs.org/ \
https://mwade31713.umwblogs.org/ \
https://saraedwards.umwblogs.org/ \
https://kcramer31713.umwblogs.org/ \
https://rbrazier31713.umwblogs.org/ \
https://sharpthoughts.umwblogs.org/ \
https://jtdement.umwblogs.org/ \
https://rashonda.umwblogs.org/ \
https://mshaw2.umwblogs.org/ \
https://jfoster31713.umwblogs.org/ \
https://glee31713.umwblogs.org/ \
https://emilybrentonsociobody.umwblogs.org/ \
https://cfiguers.umwblogs.org/ \
https://early31713umwblogsorg.umwblogs.org/ \
https://acox2.umwblogs.org/ \
https://memory.umwblogs.org/ \
https://sriley2.umwblogs.org/ \
https://blogginfortheenvironment.umwblogs.org/ \
https://layub31713.umwblogs.org/ \
https://elizabethmontanye.umwblogs.org/ \
https://catchtheleaves.umwblogs.org/ \
https://jabraham31713.umwblogs.org/ \
https://ccaycho24.umwblogs.org/ \
https://lincoln.umwblogs.org/ \
https://bodyblog.umwblogs.org/ \
https://leelz.umwblogs.org/ \
https://medsocg400.umwblogs.org/ \
https://aiallen31713.umwblogs.org/ \
https://plantas.umwblogs.org/ \
https://bioinformatics2013.umwblogs.org/ \
https://astein.umwblogs.org/ \
https://meredithsenvironmentblog.umwblogs.org/ \
https://sdavis2.umwblogs.org/ \
https://brown5.umwblogs.org/ \
https://oregonhillcats.umwblogs.org/ \
https://debato.umwblogs.org/ \
https://jhink.umwblogs.org/ \
https://cheryl.umwblogs.org/ \
https://stark.umwblogs.org/ \
https://lymb.umwblogs.org/ \
https://khirstieanne.umwblogs.org/ \
https://keekdafa.umwblogs.org/ \
https://cameronsands.umwblogs.org/ \
https://psiunyu.umwblogs.org/ \
https://kwhitman.umwblogs.org/ \
https://shadowsingreyscale.umwblogs.org/ \
https://patsgamecultblog.umwblogs.org/ \
https://alicegillespie.umwblogs.org/ \
https://infographics2013.umwblogs.org/ \
https://insanity.umwblogs.org/ \
https://jacobhargis.umwblogs.org/ \
https://nscarbro.umwblogs.org/ \
https://anikaraja.umwblogs.org/ \
https://awhite7.umwblogs.org/ \
https://indt501demaiom.umwblogs.org/ \
https://awmartin8.umwblogs.org/ \
https://reflections500.umwblogs.org/ \
https://tedf.umwblogs.org/ \
https://bcrane.umwblogs.org/ \
https://kalling.umwblogs.org/ \
https://traciejackson.umwblogs.org/ \
https://bgeorgia.umwblogs.org/ \
https://terrafirma.umwblogs.org/ \
https://nmfarmgirl.umwblogs.org/ \
https://nmight.umwblogs.org/ \
https://kkerr.umwblogs.org/ \
https://briannanichelle.umwblogs.org/ \
https://wawright.umwblogs.org/ \
https://lanthonycruz.umwblogs.org/ \
https://lwrye.umwblogs.org/ \
https://paulsblog.umwblogs.org/ \
https://costello.umwblogs.org/ \
https://leahembreydigi.umwblogs.org/ \
https://srafeew.umwblogs.org/ \
https://natenaughton.umwblogs.org/ \
https://mgrubb.umwblogs.org/ \
https://mocwmemory2013.umwblogs.org/ \
https://kknoop.umwblogs.org/ \
https://techdino.umwblogs.org/ \
https://nelk.umwblogs.org/ \
https://plaidtiger.umwblogs.org/ \
https://eyoung2.umwblogs.org/ \
https://donaldphelps.umwblogs.org/ \
https://donaldphelps1.umwblogs.org/ \
https://davidd2013.umwblogs.org/ \
https://landandsea.umwblogs.org/ \
https://amstudies2013.umwblogs.org/ \
https://indt501ehill.umwblogs.org/ \
https://agreen6.umwblogs.org/ \
https://katieliv.umwblogs.org/ \
https://jdochney.umwblogs.org/ \
https://danbrowne.umwblogs.org/ \
https://sarahmarzec.umwblogs.org/ \
https://agilley.umwblogs.org/ \
https://connoroloughlin.umwblogs.org/ \
https://biomiles.umwblogs.org/ \
https://markscott.umwblogs.org/ \
https://baker543.umwblogs.org/ \
https://cwgeorge.umwblogs.org/ \
https://socbody.umwblogs.org/ \
https://amst20s13.umwblogs.org/ \
https://alicemg.umwblogs.org/ \
https://eswanton.umwblogs.org/ \
https://mmoody3.umwblogs.org/ \
https://briggsr.umwblogs.org/ \
https://tyroth33.umwblogs.org/ \
https://creativewritingblog.umwblogs.org/ \
https://ljaminet.umwblogs.org/ \
https://bekkawritesstuff.umwblogs.org/ \
https://natelevine.umwblogs.org/ \
https://ntabor.umwblogs.org/ \
https://rdearborn.umwblogs.org/ \
https://jillianohare.umwblogs.org/ \
https://newcwsite.umwblogs.org/ \
https://lisablake231.umwblogs.org/ \
https://write.umwblogs.org/ \
https://livesimplylovefiercely.umwblogs.org/ \
https://corellius.umwblogs.org/ \
https://bryson.umwblogs.org/ \
https://jcady.umwblogs.org/ \
https://kscheetz.umwblogs.org/ \
https://mmcaloon22.umwblogs.org/ \
https://emilyatkinson.umwblogs.org/ \
https://journey.umwblogs.org/ \
https://lmbalderson1.umwblogs.org/ \
https://jchrisman.umwblogs.org/ \
https://amandastocker.umwblogs.org/ \
https://callip09.umwblogs.org/ \
https://melaniek.umwblogs.org/ \
https://gstuebne.umwblogs.org/ \
https://acadaret.umwblogs.org/ \
https://mrodrig4.umwblogs.org/ \
https://sbirch.umwblogs.org/ \
https://ccox2.umwblogs.org/ \
https://bmeeks.umwblogs.org/ \
https://slui.umwblogs.org/ \
https://tzogranw.umwblogs.org/ \
https://fspillma.umwblogs.org/ \
https://cchristy.umwblogs.org/ \
https://amost.umwblogs.org/ \
https://daniellenicole.umwblogs.org/ \
https://mrjohnson.umwblogs.org/ \
https://hlcivilwarmem.umwblogs.org/ \
https://swresearch13.umwblogs.org/ \
https://mcrusso.umwblogs.org/ \
https://jtravis21.umwblogs.org/ \
https://clamb1.umwblogs.org/ \
https://cwebb2.umwblogs.org/ \
https://riafirth.umwblogs.org/ \
https://mvanchieri.umwblogs.org/ \
https://jlehman3.umwblogs.org/ \
https://pass.umwblogs.org/ \
https://chibibyte.umwblogs.org/ \
https://patcody.umwblogs.org/ \
https://treyscottbeardfoster.umwblogs.org/ \
https://ferriswheel.umwblogs.org/ \
https://zoepeters.umwblogs.org/ \
https://accurrent.umwblogs.org/ \
https://cfilippone.umwblogs.org/ \
https://m16rifle.umwblogs.org/ \
https://ggraham.umwblogs.org/ \
https://nimitz.umwblogs.org/ \
https://lprecord.umwblogs.org/ \
https://barbie.umwblogs.org/ \
https://creditcard.umwblogs.org/ \
https://fusioncamerasystem.umwblogs.org/ \
https://jokerz.umwblogs.org/ \
https://umwacm.umwblogs.org/ \
https://umwintermsaregistration.umwblogs.org/ \
https://kappadeltapi.umwblogs.org/ \
https://rrhthistory.umwblogs.org/ \
https://swerve.umwblogs.org/ \
https://ebullience.umwblogs.org/ \
https://epikaartspan413.umwblogs.org/ \
https://sevenstamps.umwblogs.org/ \
https://familyunit.umwblogs.org/ \
https://meghancooke.umwblogs.org/ \
https://acropp56.umwblogs.org/ \
https://teachingideas.umwblogs.org/ \
https://danielbruehl.umwblogs.org/ \
https://geographyfearumw.umwblogs.org/ \
https://fluxandflow.umwblogs.org/ \
https://metalife.umwblogs.org/ \
https://cdodrill.umwblogs.org/ \
https://along.umwblogs.org/ \
https://researchingeducation.umwblogs.org/ \
https://qualitativekylej.umwblogs.org/ \
https://aasutin.umwblogs.org/ \
https://vacancy.umwblogs.org/ \
https://tusataiwan.umwblogs.org/ \
https://chicks.umwblogs.org/ \
https://sociologyandhiphop.umwblogs.org/ \
https://socg365spring2013.umwblogs.org/ \
https://shadowofragnarok.umwblogs.org/ \
https://elektronischemusik.umwblogs.org/ \
https://rittersport.umwblogs.org/ \
https://kemp13.umwblogs.org/ \
https://robbietherobot.umwblogs.org/ \
https://dvjoseph.umwblogs.org/ \
https://moe.umwblogs.org/ \
https://blogfail.umwblogs.org/ \
https://apeculiarquest.umwblogs.org/ \
https://spedmentorteacher.umwblogs.org/ \
https://deutschewerbung.umwblogs.org/ \
https://welcometotheinferno.umwblogs.org/ \
https://battlesnails.umwblogs.org/ \
https://hopeling.umwblogs.org/ \
https://staffordjunctioncoar.umwblogs.org/ \
https://maijjeffbaijproject.umwblogs.org/ \
https://nematode.umwblogs.org/ \
https://natescomputerhelp.umwblogs.org/ \
https://aliciaagallo.umwblogs.org/ \
https://alexislayne4.umwblogs.org/ \
https://beaux.umwblogs.org/ \
https://whatsgucci.umwblogs.org/ \
https://womenarepeople.umwblogs.org/ \
https://fashionablethoughts.umwblogs.org/ \
https://mks2dollaradaychallenge.umwblogs.org/ \
https://pokedex.umwblogs.org/ \
https://athleteorculturallyfemale.umwblogs.org/ \
https://aheadley.umwblogs.org/ \
https://kellybrown.umwblogs.org/ \
https://repetitioninhorror.umwblogs.org/ \
https://saadsportfolio.umwblogs.org/ \
https://dropouttheory.umwblogs.org/ \
https://honor.umwblogs.org/ \
https://brightstreetfurniture.umwblogs.org/ \
https://bsteffey.umwblogs.org/ \
https://wright.umwblogs.org/ \
https://seannycash.umwblogs.org/ \
https://wmar9599.umwblogs.org/ \
https://jamesheim.umwblogs.org/ \
https://dlambert.umwblogs.org/ \
https://beeni09.umwblogs.org/ \
https://cdargan.umwblogs.org/ \
https://aharris94.umwblogs.org/ \
https://bjohnston.umwblogs.org/ \
https://modpoetryonline.umwblogs.org/ \
https://astridstein.umwblogs.org/ \
https://mlasalle.umwblogs.org/ \
https://siena.umwblogs.org/ \
https://womenssocceroverseas.umwblogs.org/ \
https://movingonupandaway.umwblogs.org/ \
https://thehalfrican.umwblogs.org/ \
https://swededfilmfest.umwblogs.org/ \
https://firstyear.umwblogs.org/ \
https://genderrelationtheory.umwblogs.org/ \
https://nicoleinspainsummer13.umwblogs.org/ \
https://aparisianpalette.umwblogs.org/ \
https://acraft2.umwblogs.org/ \
https://carolvbird.umwblogs.org/ \
https://beccagoestoparis.umwblogs.org/ \
https://mberry2.umwblogs.org/ \
https://thisismanchester.umwblogs.org/ \
https://lailainspain.umwblogs.org/ \
https://nuevasperspectivas.umwblogs.org/ \
https://andrewdenn.umwblogs.org/ \
https://bcostach.umwblogs.org/ \
https://holohumsum13.umwblogs.org/ \
https://mdflstern.umwblogs.org/ \
https://histmental.umwblogs.org/ \
https://spain2013.umwblogs.org/ \
https://avegodsk.umwblogs.org/ \
https://giftedcollab.umwblogs.org/ \
https://fernsebner297.umwblogs.org/ \
https://scholarshiprecipients.umwblogs.org/ \
https://benches.umwblogs.org/ \
https://smallridge.umwblogs.org/ \
https://dislit2013.umwblogs.org/ \
https://wildeworld2013.umwblogs.org/ \
https://cklein3.umwblogs.org/ \
https://saintpierreaulnay.umwblogs.org/ \
https://saintpierredelatouraulnay.umwblogs.org/ \
https://mlundqui.umwblogs.org/ \
https://worldmusic.umwblogs.org/ \
https://dailycongress.umwblogs.org/ \
https://theory3.umwblogs.org/ \
https://transmedia.umwblogs.org/ \
https://hist327.umwblogs.org/ \
https://africanamericanreligions.umwblogs.org/ \
https://dgst101.umwblogs.org/ \
https://ethicslitf13.umwblogs.org/ \
https://scanlon295f13.umwblogs.org/ \
https://truecrime.umwblogs.org/ \
https://jlarochellefsem13.umwblogs.org/ \
https://nlively82.umwblogs.org/ \
https://hisp323.umwblogs.org/ \
https://jlarochelle34513.umwblogs.org/ \
https://hist386.umwblogs.org/ \
https://jpdrewniak.umwblogs.org/ \
https://bmiller5.umwblogs.org/ \
https://withers501indt.umwblogs.org/ \
https://glowworm.umwblogs.org/ \
https://clarned.umwblogs.org/ \
https://ecraige.umwblogs.org/ \
https://ktoussan297.umwblogs.org/ \
https://marriaza.umwblogs.org/ \
https://mentalmoore.umwblogs.org/ \
https://crumpfhist360.umwblogs.org/ \
https://scott471.umwblogs.org/ \
https://jjourdanusmi.umwblogs.org/ \
https://megvan84.umwblogs.org/ \
https://lgallo.umwblogs.org/ \
https://hist471ccollier.umwblogs.org/ \
https://clatane.umwblogs.org/ \
https://sdimickfsem13.umwblogs.org/ \
https://lizziesamuelsen.umwblogs.org/ \
https://gbuyze.umwblogs.org/ \
https://tstclair.umwblogs.org/ \
https://awhite7501.umwblogs.org/ \
https://samanthavarljen.umwblogs.org/ \
https://jclark7.umwblogs.org/ \
https://jessica23scatchard.umwblogs.org/ \
https://spinto34513.umwblogs.org/ \
https://msmetts.umwblogs.org/ \
https://lleaman.umwblogs.org/ \
https://cgallagher.umwblogs.org/ \
https://jnholwick.umwblogs.org/ \
https://jswank.umwblogs.org/ \
https://kaitthecaptain.umwblogs.org/ \
https://aabrams.umwblogs.org/ \
https://crchin.umwblogs.org/ \
https://whataboutgifted.umwblogs.org/ \
https://cfiliaultfsem13.umwblogs.org/ \
https://jswank1.umwblogs.org/ \
https://psmith34513.umwblogs.org/ \
https://hist485.umwblogs.org/ \
https://ronnies471experience.umwblogs.org/ \
https://macleodgiftedreflection.umwblogs.org/ \
https://as45.umwblogs.org/