#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://gsousa.umwblogs.org/ \
https://twithers.umwblogs.org/ \
https://riley.umwblogs.org/ \
https://clcmanagement.umwblogs.org/ \
https://tristanrosenberry.umwblogs.org/ \
https://learntomanage.umwblogs.org/ \
https://cristinasantos.umwblogs.org/ \
https://hbeishfsem17.umwblogs.org/ \
https://elizaanders.umwblogs.org/ \
https://megancary.umwblogs.org/ \
https://mcaryfsem17.umwblogs.org/ \
https://hollymirwin.umwblogs.org/ \
https://adownsart.umwblogs.org/ \
https://brigeddingsblog.umwblogs.org/ \
https://davidsonm.umwblogs.org/ \
https://jontruba.umwblogs.org/ \
https://understandingdevelopmentaldelays.umwblogs.org/ \
https://pminkler.umwblogs.org/ \
https://mwelsh2.umwblogs.org/ \
https://rholnick.umwblogs.org/ \
https://gshowalterfsem17.umwblogs.org/ \
https://nrosen.umwblogs.org/ \
https://livthearts.umwblogs.org/ \
https://jwaterma.umwblogs.org/ \
https://conormacmurdy.umwblogs.org/ \
https://alannahmiller.umwblogs.org/ \
https://ahaynes.umwblogs.org/ \
https://ryancho.umwblogs.org/ \
https://cynthiamanagement.umwblogs.org/ \
https://mollierhoades.umwblogs.org/ \
https://ceceburkett.umwblogs.org/ \
https://avilliva.umwblogs.org/ \
https://zcooper34517.umwblogs.org/ \
https://withoutaclue.umwblogs.org/ \
https://hduncanarts.umwblogs.org/ \
https://ahsene.umwblogs.org/ \
https://kottomanelli.umwblogs.org/ \
https://jhurnyak.umwblogs.org/ \
https://mbus525fryer.umwblogs.org/ \
https://dchriste.umwblogs.org/ \
https://digicado.umwblogs.org/ \
https://bmahone2.umwblogs.org/ \
https://sbennet2.umwblogs.org/ \
https://spaynefsem17.umwblogs.org/ \
https://shanesartsandsmarts.umwblogs.org/ \
https://mdenm8lc.umwblogs.org/ \
https://fwright.umwblogs.org/ \
https://rnunnall.umwblogs.org/ \
https://caridandavis.umwblogs.org/ \
https://cmarsala.umwblogs.org/ \
https://ddoolin1.umwblogs.org/ \
https://ndepelteau.umwblogs.org/ \
https://eeames.umwblogs.org/ \
https://thatton.umwblogs.org/ \
https://lking17345.umwblogs.org/ \
https://rachelhicksart.umwblogs.org/ \
https://cslocum.umwblogs.org/ \
https://rfullen.umwblogs.org/ \
https://nathaninfanti.umwblogs.org/ \
https://digi104jw.umwblogs.org/ \
https://alexishalldigi104.umwblogs.org/ \
https://dwalley.umwblogs.org/ \
https://savannahboyd.umwblogs.org/ \
https://kcollin2.umwblogs.org/ \
https://michaelenis.umwblogs.org/ \
https://aarondyke.umwblogs.org/ \
https://bigd0512.umwblogs.org/ \
https://mooreryanc.umwblogs.org/ \
https://dortiz.umwblogs.org/ \
https://jgellmanfsem17.umwblogs.org/ \
https://chughesfsem17.umwblogs.org/ \
https://kwatkins34517.umwblogs.org/ \
https://cmarino34517.umwblogs.org/ \
https://jboelsche34517.umwblogs.org/ \
https://sierrakatemccahon7.umwblogs.org/ \
https://econversefsem17.umwblogs.org/ \
https://4dudesingreen.umwblogs.org/ \
https://stegler.umwblogs.org/ \
https://jncourts34517.umwblogs.org/ \
https://yabhayba99.umwblogs.org/ \
https://ssherman34517.umwblogs.org/ \
https://msarlo.umwblogs.org/ \
https://indt501addambaxter.umwblogs.org/ \
https://mrscardwell.umwblogs.org/ \
https://sdflora.umwblogs.org/ \
https://natalielkloo.umwblogs.org/ \
https://roygbiv.umwblogs.org/ \
https://demerstesl.umwblogs.org/ \
https://jesshay2.umwblogs.org/ \
https://mistermalone.umwblogs.org/ \
https://skyelombardo.umwblogs.org/ \
https://dmw5.umwblogs.org/ \
https://cassandrabarlow.umwblogs.org/ \
https://eriteach.umwblogs.org/ \
https://davidesl.umwblogs.org/ \
https://jdawson.umwblogs.org/ \
https://jalb2017.umwblogs.org/ \
https://team6mgmt.umwblogs.org/ \
https://eorellanafsem17.umwblogs.org/ \
https://jcolchado34517.umwblogs.org/ \
https://mgmt301formationsquad.umwblogs.org/ \
https://imonlyheresoidontgetanf.umwblogs.org/ \
https://hmadconsulting.umwblogs.org/ \
https://notoriousmgmt.umwblogs.org/ \
https://plath.umwblogs.org/ \
https://barelymanaging.umwblogs.org/ \
https://hungrybrainsathazelhill.umwblogs.org/ \
https://leaderoftheplaquedds.umwblogs.org/ \
https://mgmtthriving.umwblogs.org/ \
https://lauraarmentrout.umwblogs.org/ \
https://bigmoneyballerz.umwblogs.org/ \
https://ntousleyfsem.umwblogs.org/ \
https://sroperindt501.umwblogs.org/ \
https://yungscullybby.umwblogs.org/ \
https://applieddigitalstudies.umwblogs.org/ \
https://runningonempty.umwblogs.org/ \
https://lydiasamson.umwblogs.org/ \
https://carrthomps.umwblogs.org/ \
https://livurtruth.umwblogs.org/ \
https://ntaylor033.umwblogs.org/ \
https://severett.umwblogs.org/ \
https://edellarova.umwblogs.org/ \
https://floundering41.umwblogs.org/ \
https://jdawsonedu.umwblogs.org/ \
https://marytilford.umwblogs.org/ \
https://mscrum.umwblogs.org/ \
https://dquigley.umwblogs.org/ \
https://span345anames.umwblogs.org/ \
https://americanstudies.umwblogs.org/ \
https://angelicagaughran.umwblogs.org/ \
https://ebledsoe.umwblogs.org/ \
https://geographiesofchildren.umwblogs.org/ \
https://viragowomen.umwblogs.org/ \
https://biochemfa2017s2.umwblogs.org/ \
https://dianavillar8.umwblogs.org/ \
https://jbramnick.umwblogs.org/ \
https://umworec.umwblogs.org/ \
https://orecresource.umwblogs.org/