#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://gunnarpoetry.umwblogs.org/ \
https://jamison302prose.umwblogs.org/ \
https://engl386notsferatu.umwblogs.org/ \
https://strugglebus.umwblogs.org/ \
https://tptravelguide.umwblogs.org/ \
https://doessnapmakeyousnap.umwblogs.org/ \
https://zachwsnapchallenge.umwblogs.org/ \
https://asnapoflife.umwblogs.org/ \
https://jwboardway.umwblogs.org/ \
https://hmarstelsnapchallenge.umwblogs.org/ \
https://snapchallenge.umwblogs.org/ \
https://laurelstone2017.umwblogs.org/ \
https://jackinthebox43.umwblogs.org/ \
https://raesharrieff.umwblogs.org/ \
https://erincb.umwblogs.org/ \
https://biancadittmannsnap.umwblogs.org/ \
https://biochemfa2016s1.umwblogs.org/ \
https://biochemfa2016s2.umwblogs.org/ \
https://slotacinemagraphs.umwblogs.org/ \
https://joyce.umwblogs.org/ \
https://mymansdurkheim.umwblogs.org/ \
https://csherma2.umwblogs.org/ \
https://pakistaneducation.umwblogs.org/ \
https://skerns.umwblogs.org/ \
https://foundinfredericksburg.umwblogs.org/ \
https://ajking98.umwblogs.org/ \
https://communitysafety.umwblogs.org/ \
https://slotaresume.umwblogs.org/ \
https://mikeybarnes1503.umwblogs.org/ \
https://mgallag2.umwblogs.org/ \
https://sierralilliestudios.umwblogs.org/ \
https://brl17.umwblogs.org/ \
https://bvl17.umwblogs.org/ \
https://ethicsandlits17.umwblogs.org/ \
https://history298.umwblogs.org/ \
https://awastelandofonesown.umwblogs.org/ \
https://margaretsutton.umwblogs.org/ \
https://cparrot2.umwblogs.org/ \
https://dlamoy2.umwblogs.org/ \
https://edci506shelleypalosky.umwblogs.org/ \
https://cpotter.umwblogs.org/ \
https://rachellynneperkins.umwblogs.org/ \
https://lailashaikh.umwblogs.org/ \
https://heidistermer.umwblogs.org/ \
https://mmiddleton.umwblogs.org/ \
https://edci506amandascheel.umwblogs.org/ \
https://cmerz.umwblogs.org/ \
https://meganmills.umwblogs.org/ \
https://dallastarkentondigiblog.umwblogs.org/ \
https://tmoore3.umwblogs.org/ \
https://abeamer.umwblogs.org/ \
https://aranzadorival.umwblogs.org/ \
https://americanfoodayelmo.umwblogs.org/ \
https://abryant5.umwblogs.org/ \
https://kcmun21.umwblogs.org/ \
https://dajuana24.umwblogs.org/ \
https://wpost.umwblogs.org/ \
https://theozotos.umwblogs.org/ \
https://esmeralda.umwblogs.org/ \
https://caballero.umwblogs.org/ \
https://law4me.umwblogs.org/ \
https://jdavis9.umwblogs.org/ \
https://neaton.umwblogs.org/ \
https://amberthesloth.umwblogs.org/ \
https://brittanymcbride.umwblogs.org/ \
https://rjwash.umwblogs.org/ \
https://amackritis.umwblogs.org/ \
https://ianingradschool.umwblogs.org/ \
https://lauradigi2017.umwblogs.org/ \
https://fmfinternshipmconnor.umwblogs.org/ \
https://mreynolds2.umwblogs.org/ \
https://grampam.umwblogs.org/ \
https://vgarrett.umwblogs.org/ \
https://jmullins50617.umwblogs.org/ \
https://ccurrin.umwblogs.org/ \
https://rfaust.umwblogs.org/ \
https://mburnsart.umwblogs.org/ \
https://yourownthing.umwblogs.org/ \
https://sarahdavies.umwblogs.org/ \
https://kbeucler.umwblogs.org/ \
https://sarahebs.umwblogs.org/ \
https://rsixpoetry.umwblogs.org/ \
https://creativespace.umwblogs.org/ \
https://umwpoemsandfiction.umwblogs.org/ \
https://cplanton.umwblogs.org/ \
https://aspinks.umwblogs.org/ \
https://annikatroutman.umwblogs.org/ \
https://bdust.umwblogs.org/ \
https://cpope.umwblogs.org/ \
https://poetryandcreativewritingzdc.umwblogs.org/ \
https://msander3.umwblogs.org/ \
https://dalaney105.umwblogs.org/ \
https://acpoetryandthings.umwblogs.org/ \
https://abigailcreativewriting.umwblogs.org/ \
https://esavariadgst.umwblogs.org/ \
https://lmanuel.umwblogs.org/ \
https://icarlyle.umwblogs.org/ \
https://mtaylor8.umwblogs.org/ \
https://cohodges.umwblogs.org/ \
https://camerontheteacher.umwblogs.org/ \
https://scampbellhartley.umwblogs.org/ \
https://diegobust4545.umwblogs.org/ \
https://marcusmitra.umwblogs.org/ \
https://blakeshowers.umwblogs.org/ \
https://digidestined.umwblogs.org/ \
https://digivft.umwblogs.org/ \
https://banamancantan.umwblogs.org/ \
https://bgoulet.umwblogs.org/ \
https://austinorourke.umwblogs.org/ \
https://aliehshabs.umwblogs.org/ \
https://robmacroseminar.umwblogs.org/ \
https://nikitakorovin.umwblogs.org/ \
https://nikitakorovin.umwblogs.org/ \
https://indt501scportfolio.umwblogs.org/ \
https://catparrotte.umwblogs.org/ \
https://mkhaziran.umwblogs.org/ \
https://rlpart104.umwblogs.org/ \
https://dgstbarnes.umwblogs.org/ \
https://heathered.umwblogs.org/ \
https://nickelson.umwblogs.org/ \
https://jvernonart.umwblogs.org/ \
https://mollyann4.umwblogs.org/ \
https://digitalfuego.umwblogs.org/ \
https://aweather.umwblogs.org/ \
https://ngraves.umwblogs.org/ \
https://mssameyer.umwblogs.org/ \
https://edunstan.umwblogs.org/ \
https://ethanoakleyedu17.umwblogs.org/ \
https://midiumwblogsorg.umwblogs.org/ \
https://teachlearntech.umwblogs.org/ \
https://jsherman501.umwblogs.org/ \
https://educ453sf.umwblogs.org/ \
https://mbenchou.umwblogs.org/ \
https://educ453.umwblogs.org/ \
https://testoeblog.umwblogs.org/ \
https://santhony.umwblogs.org/ \
https://edci.umwblogs.org/ \
https://emmac.umwblogs.org/ \
https://teacherdreamer.umwblogs.org/ \
https://garbagegames.umwblogs.org/ \
https://umwsea.umwblogs.org/ \
https://mediaandthebody.umwblogs.org/ \
https://dgeragh2.umwblogs.org/ \
https://qrmcandk.umwblogs.org/ \
https://mleinenqrm.umwblogs.org/ \
https://carlyandkenzieblogs.umwblogs.org/ \
https://qualitativeresearchproject.umwblogs.org/ \
https://sgorton.umwblogs.org/ \
https://socg365projectmariamandsarah.umwblogs.org/ \
https://bugsbugsbugs.umwblogs.org/ \
https://phoneage.umwblogs.org/ \
https://abaynard.umwblogs.org/ \
https://mbarneselit.umwblogs.org/ \
https://lwoodrthomas2017.umwblogs.org/ \
https://snapchallange17.umwblogs.org/ \
https://dpolson.umwblogs.org/ \
https://selfies.umwblogs.org/ \
https://qm2017spring.umwblogs.org/ \
https://rfrankl2.umwblogs.org/ \
https://asterne.umwblogs.org/ \
https://urbanfieldmethods.umwblogs.org/ \
https://rkqualsocg.umwblogs.org/ \
https://imstrange.umwblogs.org/ \
https://ismacrobroken.umwblogs.org/ \
https://arinko.umwblogs.org/ \
https://deathanddying.umwblogs.org/ \
https://liberatethefuture.umwblogs.org/ \
https://aknotteduc.umwblogs.org/ \
https://annaknotteduc.umwblogs.org/ \
https://lvdl17.umwblogs.org/ \
https://twilson5.umwblogs.org/ \
https://jwyedci506.umwblogs.org/ \
https://gjohn.umwblogs.org/ \
https://mppsum17.umwblogs.org/ \
https://gageeduc506.umwblogs.org/ \
https://slbremer.umwblogs.org/ \
https://rolk.umwblogs.org/ \
https://foundationsofamericaneducation.umwblogs.org/ \
https://flatterac.umwblogs.org/ \
https://nsmith3.umwblogs.org/ \
https://gmorris88.umwblogs.org/ \
https://rjaburto.umwblogs.org/ \
https://mjulmice9.umwblogs.org/ \
https://laurendang.umwblogs.org/ \
https://mwindsor.umwblogs.org/ \
https://devinblake2.umwblogs.org/ \
https://rahimamorshed.umwblogs.org/ \
https://ksikkenga.umwblogs.org/ \
https://mbarnes1503.umwblogs.org/ \
https://sobert.umwblogs.org/ \
https://savadventuresinbath.umwblogs.org/ \
https://adominguez.umwblogs.org/ \
https://kendrickkeener.umwblogs.org/ \
https://jgaray501.umwblogs.org/ \
https://tarateaches.umwblogs.org/ \
https://humanrights.umwblogs.org/ \
https://hollyabroad.umwblogs.org/ \
https://ccurrinparis.umwblogs.org/ \
https://jcollin2.umwblogs.org/ \
https://clairearoundtheworld.umwblogs.org/ \
https://rowopo.umwblogs.org/ \
https://dislit17.umwblogs.org/ \
https://lead.umwblogs.org/ \
https://motivation.umwblogs.org/ \
https://pgrothe.umwblogs.org/ \
https://thewombf17.umwblogs.org/ \
https://cgrudi.umwblogs.org/ \
https://asianamlitf17.umwblogs.org/ \
https://woundedplanetfsem17.umwblogs.org/ \
https://somehowshemanages.umwblogs.org/ \
https://suitsandsoftware.umwblogs.org/ \
https://abrock.umwblogs.org/ \
https://toughtomanage.umwblogs.org/ \
https://jpettyfsem17.umwblogs.org/ \
https://jlarochelle34517.umwblogs.org/ \
https://jwittig.umwblogs.org/ \
https://managementblogmc.umwblogs.org/ \
https://mgarrettfsem17.umwblogs.org/ \
https://ekaser5.umwblogs.org/ \
https://sworley.umwblogs.org/ \
https://carolinesreflections.umwblogs.org/ \
https://gfoley.umwblogs.org/ \
https://cierraashtonmckinney.umwblogs.org/ \
https://jasmineeryn.umwblogs.org/ \
https://ccummin3.umwblogs.org/ \
https://tareksblog.umwblogs.org/ \
https://mburke.umwblogs.org/ \
https://oneamongmanyviewsofbuisness.umwblogs.org/ \
https://thedarkknight.umwblogs.org/ \
https://wanttoknow.umwblogs.org/ \
https://thoughtsforkg.umwblogs.org/ \
https://edematteo.umwblogs.org/ \
https://kcanmanage.umwblogs.org/ \
https://hannahake.umwblogs.org/ \
https://dchergos.umwblogs.org/ \
https://joshuabstaley.umwblogs.org/ \
https://dreed.umwblogs.org/ \
https://dbroemme.umwblogs.org/ \
https://sophiacanbeartsytoo.umwblogs.org/ \
https://gsousa.umwblogs.org/ \
https://twithers.umwblogs.org/ \
https://riley.umwblogs.org/ \
https://clcmanagement.umwblogs.org/ \
https://tristanrosenberry.umwblogs.org/ \
https://learntomanage.umwblogs.org/ \
https://cristinasantos.umwblogs.org/ \
https://hbeishfsem17.umwblogs.org/ \
https://elizaanders.umwblogs.org/ \
https://megancary.umwblogs.org/ \
https://mcaryfsem17.umwblogs.org/ \
https://hollymirwin.umwblogs.org/ \
https://adownsart.umwblogs.org/ \
https://brigeddingsblog.umwblogs.org/ \
https://davidsonm.umwblogs.org/ \
https://jontruba.umwblogs.org/ \
https://understandingdevelopmentaldelays.umwblogs.org/ \
https://pminkler.umwblogs.org/ \
https://mwelsh2.umwblogs.org/ \
https://rholnick.umwblogs.org/ \
https://gshowalterfsem17.umwblogs.org/ \
https://nrosen.umwblogs.org/ \
https://livthearts.umwblogs.org/ \
https://jwaterma.umwblogs.org/ \
https://conormacmurdy.umwblogs.org/ \
https://alannahmiller.umwblogs.org/ \
https://ahaynes.umwblogs.org/ \
https://ryancho.umwblogs.org/ \
https://cynthiamanagement.umwblogs.org/ \
https://mollierhoades.umwblogs.org/ \
https://ceceburkett.umwblogs.org/ \
https://avilliva.umwblogs.org/ \
https://zcooper34517.umwblogs.org/ \
https://withoutaclue.umwblogs.org/ \
https://hduncanarts.umwblogs.org/ \
https://ahsene.umwblogs.org/ \
https://kottomanelli.umwblogs.org/ \
https://jhurnyak.umwblogs.org/ \
https://mbus525fryer.umwblogs.org/ \
https://dchriste.umwblogs.org/ \
https://digicado.umwblogs.org/ \
https://bmahone2.umwblogs.org/ \
https://sbennet2.umwblogs.org/ \
https://spaynefsem17.umwblogs.org/ \
https://shanesartsandsmarts.umwblogs.org/ \
https://mdenm8lc.umwblogs.org/ \
https://fwright.umwblogs.org/ \
https://rnunnall.umwblogs.org/ \
https://caridandavis.umwblogs.org/ \
https://cmarsala.umwblogs.org/ \
https://ddoolin1.umwblogs.org/ \
https://ndepelteau.umwblogs.org/ \
https://eeames.umwblogs.org/ \
https://thatton.umwblogs.org/ \
https://lking17345.umwblogs.org/ \
https://rachelhicksart.umwblogs.org/ \
https://cslocum.umwblogs.org/ \
https://rfullen.umwblogs.org/ \
https://nathaninfanti.umwblogs.org/ \
https://digi104jw.umwblogs.org/ \
https://alexishalldigi104.umwblogs.org/ \
https://dwalley.umwblogs.org/ \
https://savannahboyd.umwblogs.org/ \
https://kcollin2.umwblogs.org/ \
https://michaelenis.umwblogs.org/ \
https://aarondyke.umwblogs.org/ \
https://bigd0512.umwblogs.org/ \
https://mooreryanc.umwblogs.org/ \
https://dortiz.umwblogs.org/ \
https://jgellmanfsem17.umwblogs.org/ \
https://chughesfsem17.umwblogs.org/ \
https://kwatkins34517.umwblogs.org/ \
https://cmarino34517.umwblogs.org/ \
https://jboelsche34517.umwblogs.org/ \
https://sierrakatemccahon7.umwblogs.org/ \
https://econversefsem17.umwblogs.org/ \
https://4dudesingreen.umwblogs.org/ \
https://stegler.umwblogs.org/ \
https://jncourts34517.umwblogs.org/ \
https://yabhayba99.umwblogs.org/ \
https://ssherman34517.umwblogs.org/ \
https://msarlo.umwblogs.org/ \
https://indt501addambaxter.umwblogs.org/ \
https://mrscardwell.umwblogs.org/ \
https://sdflora.umwblogs.org/ \
https://natalielkloo.umwblogs.org/ \
https://roygbiv.umwblogs.org/ \
https://demerstesl.umwblogs.org/ \
https://jesshay2.umwblogs.org/ \
https://mistermalone.umwblogs.org/ \
https://skyelombardo.umwblogs.org/ \
https://dmw5.umwblogs.org/ \
https://cassandrabarlow.umwblogs.org/ \
https://eriteach.umwblogs.org/ \
https://davidesl.umwblogs.org/ \
https://jdawson.umwblogs.org/ \
https://jalb2017.umwblogs.org/ \
https://team6mgmt.umwblogs.org/ \
https://eorellanafsem17.umwblogs.org/ \
https://jcolchado34517.umwblogs.org/ \
https://mgmt301formationsquad.umwblogs.org/ \
https://imonlyheresoidontgetanf.umwblogs.org/ \
https://hmadconsulting.umwblogs.org/ \
https://notoriousmgmt.umwblogs.org/ \
https://plath.umwblogs.org/ \
https://barelymanaging.umwblogs.org/ \
https://hungrybrainsathazelhill.umwblogs.org/ \
https://leaderoftheplaquedds.umwblogs.org/ \
https://mgmtthriving.umwblogs.org/ \
https://lauraarmentrout.umwblogs.org/ \
https://bigmoneyballerz.umwblogs.org/ \
https://ntousleyfsem.umwblogs.org/ \
https://sroperindt501.umwblogs.org/ \
https://yungscullybby.umwblogs.org/ \
https://applieddigitalstudies.umwblogs.org/ \
https://runningonempty.umwblogs.org/ \
https://lydiasamson.umwblogs.org/ \
https://carrthomps.umwblogs.org/ \
https://livurtruth.umwblogs.org/ \
https://ntaylor033.umwblogs.org/ \
https://severett.umwblogs.org/ \
https://edellarova.umwblogs.org/ \
https://floundering41.umwblogs.org/ \
https://jdawsonedu.umwblogs.org/ \
https://marytilford.umwblogs.org/ \
https://mscrum.umwblogs.org/ \
https://dquigley.umwblogs.org/ \
https://span345anames.umwblogs.org/ \
https://americanstudies.umwblogs.org/ \
https://angelicagaughran.umwblogs.org/ \
https://ebledsoe.umwblogs.org/ \
https://geographiesofchildren.umwblogs.org/ \
https://viragowomen.umwblogs.org/ \
https://biochemfa2017s2.umwblogs.org/ \
https://dianavillar8.umwblogs.org/ \
https://jbramnick.umwblogs.org/ \
https://umworec.umwblogs.org/ \
https://orecresource.umwblogs.org/