#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://ethicsandlit.umwblogs.org/ \
https://siteredesign.umwblogs.org/ \
https://mosaics.umwblogs.org/ \
https://scosmos.umwblogs.org/ \
https://cttuley.umwblogs.org/ \
https://aiscat317.umwblogs.org/ \
https://mandy04.umwblogs.org/ \
https://biol121fall08.umwblogs.org/ \
https://lbirney31708.umwblogs.org/ \
https://cgonzalez31708.umwblogs.org/ \
https://bmastrorilli31708.umwblogs.org/ \
https://jwdrury.umwblogs.org/ \
https://cbyers31708.umwblogs.org/ \
https://jstlawrence.umwblogs.org/ \
https://hhousley.umwblogs.org/ \
https://cgfsem.umwblogs.org/ \
https://jhicks31708.umwblogs.org/ \
https://stephanie.umwblogs.org/ \
https://across31708.umwblogs.org/ \
https://kknopf.umwblogs.org/ \
https://bmk31708.umwblogs.org/ \
https://hmarkiewicz31708.umwblogs.org/ \
https://jthornto.umwblogs.org/ \
https://jmattos320c08.umwblogs.org/ \
https://canderso.umwblogs.org/ \
https://kam2010.umwblogs.org/ \
https://irene.umwblogs.org/ \
https://lfrench.umwblogs.org/ \
https://llbennett90.umwblogs.org/ \
https://kdemazza320c08.umwblogs.org/ \
https://cstanley320c08.umwblogs.org/ \
https://chemandsoc.umwblogs.org/ \
https://amsmith.umwblogs.org/ \
https://brandy.umwblogs.org/ \
https://bburnet3.umwblogs.org/ \
https://lorfrench.umwblogs.org/ \
https://margaret.umwblogs.org/ \
https://valerina.umwblogs.org/ \
https://zhendrix.umwblogs.org/ \
https://danceduck.umwblogs.org/ \
https://jsmith6.umwblogs.org/ \
https://eklein320c08.umwblogs.org/ \
https://biology121blog.umwblogs.org/ \
https://kimhutcheson.umwblogs.org/ \
https://katematta.umwblogs.org/ \
https://adonnell.umwblogs.org/ \
https://ssadick.umwblogs.org/ \
https://cmitchel.umwblogs.org/ \
https://nmoskal.umwblogs.org/ \
https://mohammadmesbahi.umwblogs.org/ \
https://mabbott.umwblogs.org/ \
https://hcwoll.umwblogs.org/ \
https://200ok.umwblogs.org/ \
https://srizzi.umwblogs.org/ \
https://beli.umwblogs.org/ \
https://grangell.umwblogs.org/ \
https://ahowland.umwblogs.org/ \
https://studio.umwblogs.org/ \
https://ssueiro320c08.umwblogs.org/ \
https://april18.umwblogs.org/ \
https://cprobst.umwblogs.org/ \
https://artsyniki.umwblogs.org/ \
https://megs1726.umwblogs.org/ \
https://erinoneal.umwblogs.org/ \
https://corbint.umwblogs.org/ \
https://peagle.umwblogs.org/ \
https://ey1220.umwblogs.org/ \
https://nvill0ub.umwblogs.org/ \
https://sometimesblog.umwblogs.org/ \
https://mguzman.umwblogs.org/ \
https://cellblog.umwblogs.org/ \
https://catkinso8469.umwblogs.org/ \
https://jeehye.umwblogs.org/ \
https://smatts.umwblogs.org/ \
https://soccerncheer.umwblogs.org/ \
https://cvance.umwblogs.org/ \
https://biology211.umwblogs.org/ \
https://givemebutterflies.umwblogs.org/ \
https://mcasim.umwblogs.org/ \
https://biology.umwblogs.org/ \
https://econrad31708.umwblogs.org/ \
https://chrismillerjr.umwblogs.org/ \
https://hmerkle.umwblogs.org/ \
https://biology121.umwblogs.org/ \
https://amacqueen.umwblogs.org/ \
https://rwill1zx.umwblogs.org/ \
https://gisc200.umwblogs.org/ \
https://moruejordan.umwblogs.org/ \
https://smoore3.umwblogs.org/ \
https://ncathan.umwblogs.org/ \
https://virginiabirdsnet.umwblogs.org/ \
https://econklin.umwblogs.org/ \
https://thecoleman714.umwblogs.org/ \
https://khouston.umwblogs.org/ \
https://julia12.umwblogs.org/ \
https://kwillia2.umwblogs.org/ \
https://acoyl2bg.umwblogs.org/ \
https://meghanns.umwblogs.org/ \
https://meghanclay.umwblogs.org/ \
https://manda.umwblogs.org/ \
https://khill.umwblogs.org/ \
https://sjordan.umwblogs.org/ \
https://nbrandt.umwblogs.org/ \
https://bhagen.umwblogs.org/ \
https://sbasham.umwblogs.org/ \
https://kpowell.umwblogs.org/ \
https://mhanes.umwblogs.org/ \
https://abecken.umwblogs.org/ \
https://mandasimmons.umwblogs.org/ \
https://ehopkinsit.umwblogs.org/ \
https://lvorona.umwblogs.org/ \
https://emccarth.umwblogs.org/ \
https://kstinson88.umwblogs.org/ \
https://aadams2.umwblogs.org/ \
https://sarah88.umwblogs.org/ \
https://sportch.umwblogs.org/ \
https://lic829.umwblogs.org/ \
https://achangan.umwblogs.org/ \
https://mdougher.umwblogs.org/ \
https://mackaysocialtheory.umwblogs.org/ \
https://splati.umwblogs.org/ \
https://anasocialtheory.umwblogs.org/ \
https://kiama.umwblogs.org/ \
https://hlowe.umwblogs.org/ \
https://dnegash.umwblogs.org/ \
https://ajeff2uf.umwblogs.org/ \
https://sjstrawder.umwblogs.org/ \
https://ckantwill31708.umwblogs.org/ \
https://kparvin.umwblogs.org/ \
https://abbas.umwblogs.org/ \
https://bioblog121.umwblogs.org/ \
https://eniya.umwblogs.org/ \
https://shunt.umwblogs.org/ \
https://mhenders.umwblogs.org/ \
https://iansbioblog.umwblogs.org/ \
https://efharvey.umwblogs.org/ \
https://mbobinsk.umwblogs.org/ \
https://brandyharris2.umwblogs.org/ \
https://elancast.umwblogs.org/ \
https://ataceys204blog.umwblogs.org/ \
https://rachaelflaks.umwblogs.org/ \
https://thezachattack.umwblogs.org/ \
https://vkarvela.umwblogs.org/ \
https://ajaffee.umwblogs.org/ \
https://jcho.umwblogs.org/ \
https://storyplaying.umwblogs.org/ \
https://nmuncie.umwblogs.org/ \
https://chance.umwblogs.org/ \
https://cprreview.umwblogs.org/ \
https://kellygunn.umwblogs.org/ \
https://francisemoi4.umwblogs.org/ \
https://lorfrench316.umwblogs.org/ \
https://beccafrancais.umwblogs.org/ \
https://hhopkins.umwblogs.org/ \
https://lajoiefrench316.umwblogs.org/ \
https://jesuislajeunefille.umwblogs.org/ \
https://paperclip.umwblogs.org/ \
https://lesfritesfolles.umwblogs.org/ \
https://cdoucett.umwblogs.org/ \
https://breizh.umwblogs.org/ \
https://marissaboyce.umwblogs.org/ \
https://elee.umwblogs.org/ \
https://jennmenge.umwblogs.org/ \
https://cparsons.umwblogs.org/ \
https://blumikul.umwblogs.org/ \
https://kateandpatchbordersbarriosandbiases.umwblogs.org/ \
https://marshall.umwblogs.org/ \
https://kateandpatchfsem2008.umwblogs.org/ \
https://thall.umwblogs.org/ \
https://iansesp431blog.umwblogs.org/ \
https://ahevia.umwblogs.org/ \
https://dhydorn.umwblogs.org/ \
https://strategicplanning.umwblogs.org/ \
https://bogazici09.umwblogs.org/ \
https://yeuxouverts.umwblogs.org/ \
https://edhd.umwblogs.org/ \
https://fairytalesfantasys09.umwblogs.org/ \
https://foodchem.umwblogs.org/ \
https://carlie50.umwblogs.org/ \
https://hist200c8s09.umwblogs.org/ \
https://jweinfeld.umwblogs.org/ \
https://we4kings41.umwblogs.org/ \
https://rluehrs.umwblogs.org/ \
https://asams.umwblogs.org/ \
https://vcangelo214.umwblogs.org/ \
https://mcain2.umwblogs.org/ \
https://ivaniasm.umwblogs.org/