#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://modernamericanfiction.umwblogs.org/ \
https://broadwaybabies.umwblogs.org/ \
https://williamfaulkner.umwblogs.org/ \
https://acad100.umwblogs.org/ \
https://kellygray.umwblogs.org/ \
https://megdvorak.umwblogs.org/ \
https://krechel.umwblogs.org/ \
https://ahmedlaborhist.umwblogs.org/ \
https://thea113.umwblogs.org/ \
https://klokey.umwblogs.org/ \
https://kcallaghan201.umwblogs.org/ \
https://cklaloamstudies01.umwblogs.org/ \
https://abrattch.umwblogs.org/ \
https://jennaralstore.umwblogs.org/ \
https://rthompsonlaborhist.umwblogs.org/ \
https://swatson.umwblogs.org/ \
https://kristintisdelle.umwblogs.org/ \
https://mkncwam.umwblogs.org/ \
https://nicole1960s.umwblogs.org/ \
https://gstruck.umwblogs.org/ \
https://erin202.umwblogs.org/ \
https://mbowler.umwblogs.org/ \
https://civwarsem.umwblogs.org/ \
https://samanthacorron201.umwblogs.org/ \
https://jamesamst202.umwblogs.org/ \
https://jamesamst201.umwblogs.org/ \
https://rememberingthewar.umwblogs.org/ \
https://gbush.umwblogs.org/ \
https://chuber2.umwblogs.org/ \
https://catougauthier.umwblogs.org/ \
https://mcnairblog.umwblogs.org/ \
https://letmehearyourbodytalk.umwblogs.org/ \
https://zorro16.umwblogs.org/ \
https://craitor444.umwblogs.org/ \
https://yjmoon.umwblogs.org/ \
https://amandamessick.umwblogs.org/ \
https://soc400hm.umwblogs.org/ \
https://operatest.umwblogs.org/ \
https://atennyson.umwblogs.org/ \
https://bharris.umwblogs.org/ \
https://charest201.umwblogs.org/ \
https://sfosteramst201.umwblogs.org/ \
https://oneillhist200.umwblogs.org/ \
https://jhawrami201.umwblogs.org/ \
https://kjeggleston.umwblogs.org/ \
https://moliva.umwblogs.org/ \
https://evanlaborhistory.umwblogs.org/ \
https://klmcfatr.umwblogs.org/ \
https://socgofthebody.umwblogs.org/ \
https://abicandler.umwblogs.org/ \
https://amandaamst201.umwblogs.org/ \
https://residentevil4.umwblogs.org/ \
https://idianaroberts.umwblogs.org/ \
https://kmorris.umwblogs.org/ \
https://mherdman.umwblogs.org/ \
https://prolog.umwblogs.org/ \
https://smallsurvivor.umwblogs.org/ \
https://ebcw302.umwblogs.org/ \
https://cmohrpoetry.umwblogs.org/ \
https://asisson.umwblogs.org/ \
https://sstanakz.umwblogs.org/ \
https://chrispurvis.umwblogs.org/ \
https://mgeller.umwblogs.org/ \
https://amydowd.umwblogs.org/ \
https://khroberts.umwblogs.org/ \
https://steph19.umwblogs.org/ \
https://amcclell.umwblogs.org/ \
https://roweinrome.umwblogs.org/ \
https://consciousliving.umwblogs.org/ \
https://jsmith08.umwblogs.org/ \
https://baldur.umwblogs.org/ \
https://mhudson201.umwblogs.org/ \
https://cgumw.umwblogs.org/ \
https://acollinsenvironment.umwblogs.org/ \
https://tellastorydigital.umwblogs.org/ \
https://sexualityinamericanlit.umwblogs.org/ \
https://jachelskiseniorproject.umwblogs.org/ \
https://heart.umwblogs.org/ \
https://charlottehagerman.umwblogs.org/ \
https://thewashatorialist.umwblogs.org/ \
https://elanorkindred.umwblogs.org/ \
https://cpsc401ruby.umwblogs.org/ \
https://maybeitsnotblackorwhite.umwblogs.org/ \
https://melissasoc400.umwblogs.org/ \
https://mcast.umwblogs.org/ \
https://collegebasketball.umwblogs.org/ \
https://bnick.umwblogs.org/ \
https://qualitative.umwblogs.org/ \
https://jautojphilr.umwblogs.org/ \
https://inclusionqualitativeresearch.umwblogs.org/ \
https://mwbportfolio.umwblogs.org/ \
https://hisp491a.umwblogs.org/ \
https://grippler.umwblogs.org/ \
https://qrmnichandsam.umwblogs.org/ \
https://tvanorde.umwblogs.org/ \
https://houstonsanders.umwblogs.org/ \
https://fredishome.umwblogs.org/ \
https://kzimzaz.umwblogs.org/ \
https://aqualitativeescapade.umwblogs.org/ \
https://lambersonresearch2011.umwblogs.org/ \
https://domesticviolence.umwblogs.org/ \
https://jhinojos.umwblogs.org/ \
https://portfolioredding.umwblogs.org/ \
https://jump.umwblogs.org/ \
https://theorywomen.umwblogs.org/ \
https://melissaqual365.umwblogs.org/ \
https://jovellanos.umwblogs.org/ \
https://blogsaresoinrightnow.umwblogs.org/ \
https://spaceplanning.umwblogs.org/ \
https://ddwillgru.umwblogs.org/ \
https://bmarx.umwblogs.org/ \
https://amysams88.umwblogs.org/ \
https://gary.umwblogs.org/ \
https://jfehrma2.umwblogs.org/ \
https://kelsiesnyder.umwblogs.org/ \
https://span312s11.umwblogs.org/ \
https://hotelparaiso.umwblogs.org/ \
https://chenmo1.umwblogs.org/ \
https://fashionfinder.umwblogs.org/ \
https://911stages.umwblogs.org/ \
https://samiam.umwblogs.org/ \
https://portfolio2011.umwblogs.org/ \
https://keggprojectandy.umwblogs.org/ \
https://suzerbean.umwblogs.org/ \
https://abrulatour.umwblogs.org/ \
https://smallgroup2011.umwblogs.org/ \
https://siassessment.umwblogs.org/ \
https://smarteymartey.umwblogs.org/ \
https://fruitfulwaters.umwblogs.org/ \
https://introws.umwblogs.org/ \
https://jffsemf2011.umwblogs.org/ \
https://theory11.umwblogs.org/ \
https://dot.umwblogs.org/ \
https://testbed.umwblogs.org/