#!/bin/bash

rm -rf crawls/INCOMPLETE-hist451s14/

bash archive.sh \
https://hist451s14.umwblogs.org/ \
https://hist121s14.umwblogs.org/ \
https://hist342s14.umwblogs.org/ \
https://mwade341313.umwblogs.org/ \
https://mmichniak413.umwblogs.org/ \
https://lailaescribe.umwblogs.org/ \
https://rmcghee.umwblogs.org/ \
https://morganbrown.umwblogs.org/ \
https://evansmallwood.umwblogs.org/ \
https://rosalinavanreypen.umwblogs.org/ \
https://fullmk.umwblogs.org/ \
https://psmithspan413.umwblogs.org/ \
https://anahecton.umwblogs.org/ \
https://rlbspan413.umwblogs.org/ \
https://egibbs413.umwblogs.org/ \
https://jhopkins413.umwblogs.org/ \
https://wmellott413.umwblogs.org/ \
https://wayneswifey2013.umwblogs.org/ \
https://esavaria.umwblogs.org/ \
https://robeystudentteaching.umwblogs.org/ \
https://discenvprobs.umwblogs.org/ \
https://stherria.umwblogs.org/ \
https://thejourney.umwblogs.org/ \
https://emilypatnode.umwblogs.org/ \
https://tknightecon488.umwblogs.org/ \
https://foreverglades.umwblogs.org/ \
https://mtawes.umwblogs.org/ \
https://paulaeverett.umwblogs.org/ \
https://engl305sakbari.umwblogs.org/ \
https://agutmann726.umwblogs.org/ \
https://bbyrd.umwblogs.org/ \
https://watchblog.umwblogs.org/ \
https://chucktaylor.umwblogs.org/ \
https://hannahmorgan.umwblogs.org/ \
https://ckelly4.umwblogs.org/ \
https://autumndillion.umwblogs.org/ \
https://waitingtobewritten.umwblogs.org/ \
https://khallcreativewriting.umwblogs.org/ \
https://robinsnest.umwblogs.org/ \
https://courtneycreativewriting.umwblogs.org/ \
https://eyoungcreativewriting.umwblogs.org/ \
https://garrettkearnsengl302.umwblogs.org/ \
https://kellyanne610.umwblogs.org/ \
https://zaberyeye.umwblogs.org/ \
https://ebaumgardner16.umwblogs.org/ \
https://nephthalielauture.umwblogs.org/ \
https://mwitter.umwblogs.org/ \
https://adietzen.umwblogs.org/ \
https://etruffa.umwblogs.org/ \
https://lcastellow126.umwblogs.org/ \
https://hahmed.umwblogs.org/ \
https://cvallina.umwblogs.org/ \
https://dnsresearch.umwblogs.org/ \
https://independentstudyinanonprofit.umwblogs.org/ \
https://permanentink.umwblogs.org/ \
https://goabroad.umwblogs.org/ \
https://makerbots7.umwblogs.org/ \
https://historypaul297.umwblogs.org/ \
https://gramayhistmajor.umwblogs.org/ \
https://kelseywoehnkerportfolio.umwblogs.org/ \
https://kathleenmeadteaching.umwblogs.org/ \
https://bteneyck.umwblogs.org/ \
https://hhipedsinternship.umwblogs.org/ \
https://chelseagivlereport.umwblogs.org/ \
https://education351.umwblogs.org/ \
https://rlbspan413mapa.umwblogs.org/ \
https://raceandsports.umwblogs.org/ \
https://chinesefilmgifs.umwblogs.org/ \
https://smaille.umwblogs.org/ \
https://ostdeutscholympiade.umwblogs.org/ \
https://aneyeportfolio.umwblogs.org/ \
https://psych350madelinesjournals.umwblogs.org/ \
https://gmfo2014.umwblogs.org/ \
https://gmfo2014rol.umwblogs.org/ \
https://kasmoore.umwblogs.org/ \
https://hmds106.umwblogs.org/ \
https://plongerb.umwblogs.org/ \
https://publicsoc14.umwblogs.org/ \
https://methodsfall14.umwblogs.org/ \
https://oralhistoryf14.umwblogs.org/ \
https://inventions.umwblogs.org/ \
https://amst201f14.umwblogs.org/ \
https://rarm.umwblogs.org/ \
https://hdennis.umwblogs.org/ \
https://agrace0arts104.umwblogs.org/ \
https://anotherumwblogdump.umwblogs.org/ \
https://cnichol3.umwblogs.org/ \
https://sbrana31714.umwblogs.org/ \
https://jwinterkorn31714.umwblogs.org/ \
https://lberns.umwblogs.org/ \
https://npaolicelli.umwblogs.org/ \
https://livlifetothefullest.umwblogs.org/ \
https://hopkinsinfoage.umwblogs.org/ \
https://hannahlloyd.umwblogs.org/ \
https://iahmeditrtw.umwblogs.org/ \
https://aandruli.umwblogs.org/ \
https://mobyyb.umwblogs.org/ \
https://kbintrowgst.umwblogs.org/ \
https://wgstgoodman.umwblogs.org/ \
https://adeleonwsgs.umwblogs.org/ \
https://rmaywgst.umwblogs.org/ \
https://wgstmoody.umwblogs.org/ \
https://eileenintrows.umwblogs.org/ \
https://rhasan.umwblogs.org/ \
https://veronicambwgst101.umwblogs.org/ \
https://mmccloud711.umwblogs.org/ \
https://katintrowgst.umwblogs.org/ \
https://cburkettwgst101.umwblogs.org/ \
https://pspivey15wgst.umwblogs.org/ \
https://wsesaia.umwblogs.org/ \
https://innovationstation.umwblogs.org/ \
https://whollida.umwblogs.org/ \
https://wgstjwilliams.umwblogs.org/ \
https://feministbeyonce.umwblogs.org/ \
https://wgstfantozzi.umwblogs.org/ \
https://pugsnotdrugs.umwblogs.org/ \
https://wgstblevins.umwblogs.org/ \
https://iggymonkey.umwblogs.org/ \
https://rkintrowgst.umwblogs.org/ \
https://tomtothebryson.umwblogs.org/ \
https://302palosky.umwblogs.org/ \
https://302coligan.umwblogs.org/ \
https://emilymullis.umwblogs.org/ \
https://hfisher2.umwblogs.org/ \
https://jordanpoetry302.umwblogs.org/ \
https://erinsblog.umwblogs.org/ \
https://aknott.umwblogs.org/ \
https://adofflemyer.umwblogs.org/ \
https://aknott16.umwblogs.org/ \
https://smgwmst.umwblogs.org/ \
https://ohiogirl.umwblogs.org/ \
https://302locationkb.umwblogs.org/ \
https://kapsoff2words.umwblogs.org/ \
https://kbennis.umwblogs.org/ \
https://jblackmo.umwblogs.org/ \
https://sdjames.umwblogs.org/ \
https://starspace.umwblogs.org/ \
https://ejewriting.umwblogs.org/ \
https://esimmons.umwblogs.org/ \
https://autotaco007.umwblogs.org/ \
https://bgruendl.umwblogs.org/ \
https://scrisafulli93.umwblogs.org/ \
https://mhwriting302.umwblogs.org/ \
https://mbachman.umwblogs.org/ \
https://whollidalab.umwblogs.org/ \
https://margotstorch.umwblogs.org/ \
https://engl491truecrimenarratives.umwblogs.org/ \
https://arhodeswgst101.umwblogs.org/ \
https://mreed2.umwblogs.org/ \
https://educ535hmp.umwblogs.org/ \
https://rolandpryzbylewski.umwblogs.org/ \
https://theory471final.umwblogs.org/ \
https://tyfinaltheoryproject.umwblogs.org/ \
https://artinquiryexploration.umwblogs.org/ \
https://gilmansocialtheory.umwblogs.org/ \
https://relg331.umwblogs.org/ \
https://futureeaters.umwblogs.org/ \
https://amst201s15.umwblogs.org/ \
https://abarnesarts.umwblogs.org/ \
https://saraheells.umwblogs.org/ \
https://chossler.umwblogs.org/ \
https://meghansart.umwblogs.org/ \
https://econ482sgeorge.umwblogs.org/ \
https://jcrouch2.umwblogs.org/ \
https://msmith8.umwblogs.org/ \
https://genericecon.umwblogs.org/ \
https://lucisperspective.umwblogs.org/ \
https://mintchocolatechip.umwblogs.org/ \
https://meganfowler.umwblogs.org/ \
https://johnsonlillie.umwblogs.org/ \
https://bgray92.umwblogs.org/ \
https://rshafiqeesc.umwblogs.org/ \
https://bgostelow.umwblogs.org/ \
https://karmstrong.umwblogs.org/ \
https://tdcosta.umwblogs.org/ \
https://aliceredhead.umwblogs.org/ \
https://sarahschrock.umwblogs.org/ \
https://elitpipan.umwblogs.org/ \
https://kateymatragrano.umwblogs.org/ \
https://desteph.umwblogs.org/ \
https://njudy.umwblogs.org/ \
https://bodymod.umwblogs.org/ \
https://switzerlandstories.umwblogs.org/ \
https://eportfoliojswank.umwblogs.org/ \
https://lbsstudyabroad2015.umwblogs.org/ \
https://sraflor.umwblogs.org/ \
https://hwesterv.umwblogs.org/ \
https://abroadandabout.umwblogs.org/ \
https://langlab.umwblogs.org/ \
https://psyc499fall15.umwblogs.org/ \
https://french342.umwblogs.org/ \
https://whitneypace.umwblogs.org/ \
https://tennesseewilliams.umwblogs.org/ \
https://fashiontheoryindependentstudy.umwblogs.org/ \
https://codexicon.umwblogs.org/ \
https://hlocher34515.umwblogs.org/ \
https://kganser34515.umwblogs.org/ \
https://hannahwilliams.umwblogs.org/ \
https://jakecrowleysseniorproject.umwblogs.org/ \
https://cbavc.umwblogs.org/ \
https://chloerippel.umwblogs.org/ \
https://themikebennettjr.umwblogs.org/ \
https://rlynn.umwblogs.org/ \
https://cmarche.umwblogs.org/ \
https://robbiemoore.umwblogs.org/ \
https://astudentsblog.umwblogs.org/ \
https://joshbartosch.umwblogs.org/ \
https://tagsblog.umwblogs.org/ \
https://mmeidt.umwblogs.org/ \
https://abroadiniceland.umwblogs.org/ \
https://psychofwomenspring2016.umwblogs.org/ \
https://bhutter.umwblogs.org/ \
https://hectondigi.umwblogs.org/ \
https://carolinemalec.umwblogs.org/ \
https://museumtote.umwblogs.org/ \
https://annieb.umwblogs.org/ \
https://rconcepc.umwblogs.org/ \
https://stewmuz.umwblogs.org/ \
https://nharttgep.umwblogs.org/ \
https://buchanem.umwblogs.org/ \
https://creativewriting1.umwblogs.org/ \
https://ercahoon.umwblogs.org/ \
https://jspoetry.umwblogs.org/ \
https://tinkeringjournal.umwblogs.org/ \
https://shelton553.umwblogs.org/ \
https://mbahhur4.umwblogs.org/ \
https://spassley.umwblogs.org/ \
https://amandaahmed.umwblogs.org/ \
https://qualresearch365.umwblogs.org/ \
https://galapagos2016.umwblogs.org/ \
https://thea310fashionhistoryresearchproject.umwblogs.org/ \
https://late18centurybritlit.umwblogs.org/ \
https://giftedreflections.umwblogs.org/ \
https://scireason2016.umwblogs.org/ \
https://interactivestorytelling.umwblogs.org/ \
https://interactiveteacherstorytelling.umwblogs.org/ \
https://psychofwomenfall2016.umwblogs.org/ \
https://methodsfall2016.umwblogs.org/ \
https://myhistoryesander.umwblogs.org/ \
https://droodical.umwblogs.org/ \
https://cenglis2.umwblogs.org/ \
https://elena.umwblogs.org/ \
https://mherring.umwblogs.org/ \
https://gkers.umwblogs.org/ \
https://smuz09.umwblogs.org/ \
https://fgoff302prose.umwblogs.org/ \
https://fgoff302poetry.umwblogs.org/ \
https://seniorprojectfall2016.umwblogs.org/ \
https://history324.umwblogs.org/ \
https://psyc499spring17.umwblogs.org/ \
https://qrm2017spring.umwblogs.org/ \
https://edci506hardbower.umwblogs.org/ \
https://digidump.umwblogs.org/ \
https://khartnet.umwblogs.org/ \
https://jgaray93.umwblogs.org/ \
https://gknowles13.umwblogs.org/ \
https://sophiageron.umwblogs.org/ \
https://jthomaspoems.umwblogs.org/ \
https://yagirlalexa.umwblogs.org/ \
https://frostygracie.umwblogs.org/ \
https://kkampsen.umwblogs.org/ \
https://poetryraven.umwblogs.org/ \
https://mystuff.umwblogs.org/ \
https://perfectlypassionatepoetry.umwblogs.org/ \
https://oliviabreler.umwblogs.org/ \
https://dpagano.umwblogs.org/ \
https://nickypoetry.umwblogs.org/ \
https://arianaspoetryblog.umwblogs.org/ \
https://skyofstarflowers.umwblogs.org/ \
https://ginnybixby.umwblogs.org/ \
https://creativityflowsfree.umwblogs.org/ \
https://darkrose.umwblogs.org/ \
https://aquresh2.umwblogs.org/ \
https://clr90s.umwblogs.org/ \
https://macbev.umwblogs.org/ \
https://englishteacher.umwblogs.org/ \
https://amasseyelim.umwblogs.org/ \
https://distresseddancer.umwblogs.org/ \
https://ccrusottmacbeth.umwblogs.org/ \
https://aodell92.umwblogs.org/ \
https://criticalfanfiction.umwblogs.org/ \
https://lrussell.umwblogs.org/ \
https://2turtlekitties.umwblogs.org/ \
https://ealkindi.umwblogs.org/ \
https://alyssanicole.umwblogs.org/ \
https://fuzdgy.umwblogs.org/ \
https://katdigiart.umwblogs.org/ \
https://carolineralston.umwblogs.org/ \
https://edci506s17.umwblogs.org/ \
https://bhenders.umwblogs.org/ \
https://swmcbride.umwblogs.org/ \
https://sophiesthoughts.umwblogs.org/ \
https://jjwannotations.umwblogs.org/ \
https://spaulk.umwblogs.org/ \
https://areed5.umwblogs.org/ \
https://kmacomber.umwblogs.org/ \
https://cmauck.umwblogs.org/ \
https://ekeehan.umwblogs.org/ \
https://management.umwblogs.org/ \
https://ibriones34517.umwblogs.org/ \
https://smillerporfolio.umwblogs.org/ \
https://dlowe1ud.umwblogs.org/ \
https://madisoncaron.umwblogs.org/ \
https://bkertche.umwblogs.org/ \
https://msfowler.umwblogs.org/ \
https://meidteportfolio.umwblogs.org/ \
https://nkjg.umwblogs.org/ \
https://thenack.umwblogs.org/ \
https://rjarchive.umwblogs.org/ \
https://pnguyen2.umwblogs.org/ \
https://sammcmullen22.umwblogs.org/ \
https://aschmied.umwblogs.org/ \
https://tylerray.umwblogs.org/ \
https://jschride.umwblogs.org/ \
https://emaston.umwblogs.org/ \
https://msarlo30618.umwblogs.org/ \
https://pbogeropenlearning2018.umwblogs.org/ \
https://ahblog.umwblogs.org/ \
https://zacharyhandlin.umwblogs.org/ \
https://gizmo.umwblogs.org/ \
https://kaylyncordingley.umwblogs.org/ \
https://teamtgal.umwblogs.org/ \
https://noel94.umwblogs.org/ \
https://digitalajax.umwblogs.org/ \
https://lkong2.umwblogs.org/ \
https://bbravo.umwblogs.org/ \
https://elliemakesthings.umwblogs.org/ \
https://lburke2.umwblogs.org/ \
https://jleckrone425leadership.umwblogs.org/ \
https://gchishol.umwblogs.org/ \
https://ttorres.umwblogs.org/ \
https://ericsblog.umwblogs.org/ \
https://resourcedisabilityguide.umwblogs.org/ \
https://campusafety.umwblogs.org/ \
https://rdalessa.umwblogs.org/ \
https://mpetroskey6.umwblogs.org/ \
https://carinadavis.umwblogs.org/ \
https://krytin.umwblogs.org/ \
https://cpfrimmer.umwblogs.org/ \
https://kindacts.umwblogs.org/ \
https://bswindell.umwblogs.org/ \
https://cocresearch.umwblogs.org/ \
https://ebdeducationandresources.umwblogs.org/ \
https://orivero2.umwblogs.org/ \
https://japan.umwblogs.org/ \
https://melhak.umwblogs.org/ \
https://ekachele.umwblogs.org/ \
https://thecareteam.umwblogs.org/ \
https://biochemfa2019.umwblogs.org/ \
https://amandasmith.umwblogs.org/ \
https://chrystalburroughs.umwblogs.org/ \
https://iquiroga.umwblogs.org/ \
https://hbreton451engl.umwblogs.org/ \
https://sydney.umwblogs.org/ \
https://awatring.umwblogs.org/ \
https://greenlawclone.umwblogs.org/ \
https://jswope.umwblogs.org/ \
https://alyssaonmars.umwblogs.org/ \
https://ssklar.umwblogs.org/ \
https://asharpe2.umwblogs.org/ \
https://tinkeringhackingmakingfinal.umwblogs.org/ \
https://cmaroney.umwblogs.org/ \
https://thea436exampledigitalproductionbook.umwblogs.org/ \
https://thea436exampleclassblog.umwblogs.org/ \
https://ehasting.umwblogs.org/ \
https://mccluskeyfaarinfo.umwblogs.org/ \
https://mmeiser719.umwblogs.org/ \
https://carolineturner.umwblogs.org/ \
https://meagnkim.umwblogs.org/ \
https://hewanshimeles.umwblogs.org/ \
https://hammer.umwblogs.org/ \
https://rhodaokorie.umwblogs.org/ \
https://tl11.umwblogs.org/ \
https://reviewsgalore.umwblogs.org/ \
https://polandblog.umwblogs.org/ \
https://lechtmanseniorproject.umwblogs.org/ \
https://angel24671.umwblogs.org/ \
https://436designsbyshaun.umwblogs.org/ \
https://epearsoncostumes.umwblogs.org/ \
https://portfolioforcodingclass.umwblogs.org/