#!/bin/bash

rm -rf crawls/INCOMPLETE-*

bash archive.sh \
https://mmeidt.umwblogs.org/ \
https://abroadiniceland.umwblogs.org/ \
https://psychofwomenspring2016.umwblogs.org/ \
https://bhutter.umwblogs.org/ \
https://hectondigi.umwblogs.org/ \
https://carolinemalec.umwblogs.org/ \
https://museumtote.umwblogs.org/ \
https://annieb.umwblogs.org/ \
https://rconcepc.umwblogs.org/ \
https://stewmuz.umwblogs.org/ \
https://nharttgep.umwblogs.org/ \
https://buchanem.umwblogs.org/ \
https://creativewriting1.umwblogs.org/ \
https://ercahoon.umwblogs.org/ \
https://jspoetry.umwblogs.org/ \
https://tinkeringjournal.umwblogs.org/ \
https://shelton553.umwblogs.org/ \
https://mbahhur4.umwblogs.org/ \
https://spassley.umwblogs.org/ \
https://amandaahmed.umwblogs.org/ \
https://qualresearch365.umwblogs.org/ \
https://galapagos2016.umwblogs.org/ \
https://thea310fashionhistoryresearchproject.umwblogs.org/ \
https://late18centurybritlit.umwblogs.org/ \
https://giftedreflections.umwblogs.org/ \
https://scireason2016.umwblogs.org/ \
https://interactivestorytelling.umwblogs.org/ \
https://interactiveteacherstorytelling.umwblogs.org/ \
https://psychofwomenfall2016.umwblogs.org/ \
https://methodsfall2016.umwblogs.org/ \
https://myhistoryesander.umwblogs.org/ \
https://droodical.umwblogs.org/ \
https://cenglis2.umwblogs.org/ \
https://elena.umwblogs.org/ \
https://mherring.umwblogs.org/ \
https://gkers.umwblogs.org/ \
https://smuz09.umwblogs.org/ \
https://fgoff302prose.umwblogs.org/ \
https://fgoff302poetry.umwblogs.org/ \
https://seniorprojectfall2016.umwblogs.org/ \
https://history324.umwblogs.org/ \
https://psyc499spring17.umwblogs.org/ \
https://qrm2017spring.umwblogs.org/ \
https://edci506hardbower.umwblogs.org/ \
https://digidump.umwblogs.org/ \
https://khartnet.umwblogs.org/ \
https://jgaray93.umwblogs.org/ \
https://gknowles13.umwblogs.org/ \
https://sophiageron.umwblogs.org/ \
https://jthomaspoems.umwblogs.org/ \
https://yagirlalexa.umwblogs.org/ \
https://frostygracie.umwblogs.org/ \
https://kkampsen.umwblogs.org/ \
https://poetryraven.umwblogs.org/ \
https://mystuff.umwblogs.org/ \
https://perfectlypassionatepoetry.umwblogs.org/ \
https://oliviabreler.umwblogs.org/ \
https://dpagano.umwblogs.org/ \
https://nickypoetry.umwblogs.org/ \
https://arianaspoetryblog.umwblogs.org/ \
https://skyofstarflowers.umwblogs.org/ \
https://ginnybixby.umwblogs.org/ \
https://creativityflowsfree.umwblogs.org/ \
https://darkrose.umwblogs.org/ \
https://aquresh2.umwblogs.org/ \
https://clr90s.umwblogs.org/ \
https://macbev.umwblogs.org/ \
https://englishteacher.umwblogs.org/ \
https://amasseyelim.umwblogs.org/ \
https://distresseddancer.umwblogs.org/ \
https://ccrusottmacbeth.umwblogs.org/ \
https://aodell92.umwblogs.org/ \
https://criticalfanfiction.umwblogs.org/ \
https://lrussell.umwblogs.org/ \
https://2turtlekitties.umwblogs.org/ \
https://ealkindi.umwblogs.org/ \
https://alyssanicole.umwblogs.org/ \
https://fuzdgy.umwblogs.org/ \
https://katdigiart.umwblogs.org/ \
https://carolineralston.umwblogs.org/ \
https://edci506s17.umwblogs.org/ \
https://bhenders.umwblogs.org/ \
https://swmcbride.umwblogs.org/ \
https://sophiesthoughts.umwblogs.org/ \
https://jjwannotations.umwblogs.org/ \
https://spaulk.umwblogs.org/ \
https://areed5.umwblogs.org/ \
https://kmacomber.umwblogs.org/ \
https://cmauck.umwblogs.org/ \
https://ekeehan.umwblogs.org/ \
https://management.umwblogs.org/ \
https://ibriones34517.umwblogs.org/ \
https://smillerporfolio.umwblogs.org/ \
https://dlowe1ud.umwblogs.org/ \
https://madisoncaron.umwblogs.org/ \
https://bkertche.umwblogs.org/ \
https://msfowler.umwblogs.org/ \
https://meidteportfolio.umwblogs.org/ \
https://nkjg.umwblogs.org/ \
https://thenack.umwblogs.org/ \
https://rjarchive.umwblogs.org/ \
https://pnguyen2.umwblogs.org/ \
https://sammcmullen22.umwblogs.org/ \
https://aschmied.umwblogs.org/ \
https://tylerray.umwblogs.org/ \
https://jschride.umwblogs.org/ \
https://emaston.umwblogs.org/ \
https://msarlo30618.umwblogs.org/ \
https://pbogeropenlearning2018.umwblogs.org/ \
https://ahblog.umwblogs.org/ \
https://zacharyhandlin.umwblogs.org/ \
https://gizmo.umwblogs.org/ \
https://kaylyncordingley.umwblogs.org/ \
https://teamtgal.umwblogs.org/ \
https://noel94.umwblogs.org/ \
https://digitalajax.umwblogs.org/ \
https://lkong2.umwblogs.org/ \
https://bbravo.umwblogs.org/ \
https://elliemakesthings.umwblogs.org/ \
https://lburke2.umwblogs.org/ \
https://jleckrone425leadership.umwblogs.org/ \
https://gchishol.umwblogs.org/ \
https://ttorres.umwblogs.org/ \
https://ericsblog.umwblogs.org/ \
https://resourcedisabilityguide.umwblogs.org/ \
https://campusafety.umwblogs.org/ \
https://rdalessa.umwblogs.org/ \
https://mpetroskey6.umwblogs.org/ \
https://carinadavis.umwblogs.org/ \
https://krytin.umwblogs.org/ \
https://cpfrimmer.umwblogs.org/ \
https://kindacts.umwblogs.org/ \
https://bswindell.umwblogs.org/ \
https://cocresearch.umwblogs.org/ \
https://ebdeducationandresources.umwblogs.org/ \
https://orivero2.umwblogs.org/ \
https://japan.umwblogs.org/ \
https://melhak.umwblogs.org/ \
https://ekachele.umwblogs.org/ \
https://thecareteam.umwblogs.org/ \
https://biochemfa2019.umwblogs.org/ \
https://amandasmith.umwblogs.org/ \
https://chrystalburroughs.umwblogs.org/ \
https://iquiroga.umwblogs.org/ \
https://hbreton451engl.umwblogs.org/ \
https://sydney.umwblogs.org/ \
https://awatring.umwblogs.org/ \
https://greenlawclone.umwblogs.org/ \
https://jswope.umwblogs.org/ \
https://alyssaonmars.umwblogs.org/ \
https://ssklar.umwblogs.org/ \
https://asharpe2.umwblogs.org/ \
https://tinkeringhackingmakingfinal.umwblogs.org/ \
https://cmaroney.umwblogs.org/ \
https://thea436exampledigitalproductionbook.umwblogs.org/ \
https://thea436exampleclassblog.umwblogs.org/ \
https://ehasting.umwblogs.org/ \
https://mccluskeyfaarinfo.umwblogs.org/ \
https://mmeiser719.umwblogs.org/ \
https://carolineturner.umwblogs.org/ \
https://meagnkim.umwblogs.org/ \
https://hewanshimeles.umwblogs.org/ \
https://hammer.umwblogs.org/ \
https://rhodaokorie.umwblogs.org/ \
https://tl11.umwblogs.org/ \
https://reviewsgalore.umwblogs.org/ \
https://polandblog.umwblogs.org/ \
https://lechtmanseniorproject.umwblogs.org/ \
https://angel24671.umwblogs.org/ \
https://436designsbyshaun.umwblogs.org/ \
https://epearsoncostumes.umwblogs.org/ \
https://portfolioforcodingclass.umwblogs.org/