FROM webrecorder/browsertrix-crawler:latest
RUN apt update && apt install zip wget -y
COPY index.html /index.html
COPY redirect.php /redirect.php
COPY htaccess /.htaccess
COPY webrecorder.sh /webrecorder.sh
